"use client";
import {FormEvent,useEffect,useState} from "react";
import {ArrowLeft,Check,Clock3,LogIn,LogOut} from "lucide-react";
import {RescueEdLogo} from "@/components/brand-logo";
import "./attendance.css";

type Info={event:{id:string;name:string;eventDate:string;startTime:string|null;endTime:string|null};action:"come"|"leave"};

export default function AttendancePage(){
 const [info,setInfo]=useState<Info|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState("");
 const [query,setQuery]=useState({eventId:"",code:"",mode:"come" as "come"|"leave"});
 useEffect(()=>{const params=new URLSearchParams(location.search),next={eventId:params.get("eventId")||"",code:params.get("code")||"",mode:(params.get("mode")==="leave"?"leave":"come") as "come"|"leave"};setQuery(next);fetch(`/api/attendance?eventId=${encodeURIComponent(next.eventId)}&code=${encodeURIComponent(next.code)}&mode=${next.mode}`).then(async response=>{const data=await response.json() as Info&{error?:string};if(!response.ok)throw new Error(data.error);setInfo(data)}).catch(reason=>setError(reason instanceof Error?reason.message:"QR-Code konnte nicht gelesen werden."))},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget),helperToken=localStorage.getItem(`rescueed-helper-${query.eventId}`)||"";try{const response=await fetch("/api/attendance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventId:query.eventId,code:query.code,action:query.mode,firstName:form.get("firstName"),lastName:form.get("lastName"),qualification:form.get("qualification"),helperToken})}),data=await response.json() as {error?:string;helperToken?:string};if(!response.ok)throw new Error(data.error);if(data.helperToken)localStorage.setItem(`rescueed-helper-${query.eventId}`,data.helperToken);if(query.mode==="leave")localStorage.removeItem(`rescueed-helper-${query.eventId}`);setDone(query.mode==="come"?"Du bist jetzt als anwesend eingecheckt.":"Du wurdest erfolgreich als gegangen erfasst.")}catch(reason){setError(reason instanceof Error?reason.message:"Anwesenheit konnte nicht gespeichert werden.")}finally{setBusy(false)}}
 return <main className="attendance-page"><a className="attendance-back" href="/"><ArrowLeft/> Zur Startseite</a><section className="attendance-card"><header><RescueEdLogo className="brand-logo--attendance"/><div><b>RescueEd Alert</b><span>Anwesenheit erfassen</span></div></header>{error&&!info?<div className="attendance-state error"><b>QR-Code nicht gültig</b><p>{error}</p></div>:info&&<><div className="attendance-event"><small>{query.mode==="come"?"KOMMEN":"GEHEN"}</small><h1>{info.event.name}</h1><p><Clock3/> {new Intl.DateTimeFormat("de-DE",{dateStyle:"long"}).format(new Date(info.event.eventDate+"T12:00:00"))}{info.event.startTime&&info.event.endTime?` · ${info.event.startTime}–${info.event.endTime} Uhr`:""}</p></div>{done?<div className="attendance-state success"><Check/><b>{done}</b><p>Du kannst diese Seite jetzt schließen.</p></div>:<form onSubmit={submit}>{query.mode==="come"?<><label>Vorname<input name="firstName" required autoComplete="given-name"/></label><label>Nachname<input name="lastName" required autoComplete="family-name"/></label><label>Qualifikation<input name="qualification" required placeholder="z. B. Rettungssanitäter/in"/></label></>:<div className="leave-note"><LogOut/><p>Beim Bestätigen wird deine Anwesenheit mit der aktuellen Uhrzeit beendet. Verwende dasselbe Gerät wie beim Kommen.</p></div>}{error&&<p className="attendance-error" role="alert">{error}</p>}<button disabled={busy}>{query.mode==="come"?<LogIn/>:<LogOut/>}{busy?"Wird gespeichert …":query.mode==="come"?"Jetzt einchecken":"Gehen bestätigen"}</button></form>}</>}</section></main>
}
