"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {AlertTriangle,BellRing,Check,ChevronDown,Copy,Download,FileDown,FileText,House,LogOut,MailCheck,Plus,Printer,QrCode,ShieldCheck,Trash2,UserMinus,UserPlus,Users,X} from "lucide-react";
import {RescueEdLogo} from "@/components/brand-logo";
import "./event-dashboard.css";
import "./event-dashboard-details.css";
import "./qr-export.css";

type Assignment={id:string;name:string;operationalStatus:"available"|"deployed";deployedAt:string|null;clearedAt:string|null};
type Helper={id:string;name:string;firstName:string|null;lastName:string|null;qualification:string;assignmentId:string|null;assignmentName:string|null;registeredAt:string;removedAt:string|null};
type Detail={event:{id:string;name:string;eventDate:string;endDate:string;startTime:string|null;endTime:string|null;helperLimit:number;priceCents:number;currency:string;status:string;createdAt:string};invoice:{id:string;recipientName:string;street:string;postalCode:string;city:string;email:string;amountCents:number;status:string;createdAt:string}|null;assignments:Assignment[];helpers:Helper[];attendanceLinks:{come:string;leave:string}};

function Brand(){return <div className="flex items-center gap-3"><RescueEdLogo/><div><b>RescueEd Alert</b><p>Einchecken · Einteilen · Alarmieren</p></div></div>}
function fmtDate(value:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"long"}).format(new Date(value.includes("T")?value:value+"T12:00:00"))}
function fmtTime(value:string|null){return value?new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"–"}
function displayName(person:Helper){if(person.lastName)return `${person.lastName}, ${person.firstName||""}`.trim();const parts=person.name.trim().split(/\s+/);return parts.length>1?`${parts.at(-1)}, ${parts.slice(0,-1).join(" ")}`:person.name}

export function ConnectedDashboard({eventId,home,logout}:{eventId:string;home:()=>void;logout:()=>void}){
 const [data,setData]=useState<Detail|null>(null),[error,setError]=useState(""),[dialog,setDialog]=useState<"details"|"qr"|"unit"|"unit-delete"|"helper"|"alert"|"delete"|"deleted"|null>(null),[newUnit,setNewUnit]=useState(""),[unitToDelete,setUnitToDelete]=useState<Assignment|null>(null),[busy,setBusy]=useState(false),[pdfBusy,setPdfBusy]=useState(false),[notice,setNotice]=useState(""),[deleted,setDeleted]=useState(false);
 const [newHelper,setNewHelper]=useState({firstName:"",lastName:"",qualification:""});
 const [selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState("");
 const load=useCallback(async()=>{if(deleted)return;try{const response=await fetch(`/api/events/${encodeURIComponent(eventId)}`,{cache:"no-store"}),next=await response.json() as Detail&{error?:string};if(response.status===401){logout();return}if(!response.ok)throw new Error(next.error);setData(next);setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Event konnte nicht geladen werden.")}},[deleted,eventId,logout]);
 useEffect(()=>{if(deleted)return;load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[deleted,load]);
 const present=useMemo(()=>data?.helpers.filter(person=>!person.removedAt)||[],[data]),assigned=present.filter(person=>person.assignmentId).length,availableUnits=data?.assignments.filter(unit=>unit.operationalStatus!=="deployed")||[],deployedUnits=data?.assignments.filter(unit=>unit.operationalStatus==="deployed")||[];
 async function addUnit(){if(!newUnit.trim())return;setBusy(true);const response=await fetch(`/api/events/${encodeURIComponent(eventId)}/assignments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:newUnit})}),result=await response.json() as {error?:string};setBusy(false);if(!response.ok){setError(result.error||"Sanitätsmittel konnte nicht angelegt werden.");return}setNewUnit("");setDialog(null);await load()}
 async function deleteUnit(){if(!unitToDelete)return;setBusy(true);setError("");const response=await fetch(`/api/events/${encodeURIComponent(eventId)}/assignments/${encodeURIComponent(unitToDelete.id)}`,{method:"DELETE",headers:{"content-type":"application/json"},body:"{}"}),result=await response.json() as {error?:string};setBusy(false);if(!response.ok){setError(result.error||"Sanitätsmittel konnte nicht gelöscht werden.");setDialog(null);await load();return}setDialog(null);setUnitToDelete(null);setNotice("Sanitätsmittel wurde gelöscht.");setTimeout(()=>setNotice(""),3500);await load()}
 async function addHelper(){if(!newHelper.firstName.trim()||!newHelper.lastName.trim()||!newHelper.qualification.trim())return;setBusy(true);setError("");const response=await fetch(`/api/events/${encodeURIComponent(eventId)}/helpers`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(newHelper)}),result=await response.json() as {error?:string};setBusy(false);if(!response.ok){setError(result.error||"Helfer konnte nicht angelegt werden.");return}setNewHelper({firstName:"",lastName:"",qualification:""});setDialog(null);setNotice("Helfer wurde als anwesend angelegt.");setTimeout(()=>setNotice(""),3500);await load()}
 async function checkoutHelper(helperId:string){setBusy(true);setError("");const response=await fetch(`/api/events/${encodeURIComponent(eventId)}/helpers/${encodeURIComponent(helperId)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"checkout"})}),result=await response.json() as {error?:string};setBusy(false);if(!response.ok){setError(result.error||"Helfer konnte nicht ausgebucht werden.");return}setNotice("Helfer wurde mit aktueller Uhrzeit ausgebucht.");setTimeout(()=>setNotice(""),3500);await load()}
 async function clearUnit(unitId:string){setBusy(true);setError("");try{const response=await fetch(`/api/events/${encodeURIComponent(eventId)}/assignments/${encodeURIComponent(unitId)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"clear"})}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Sanitätsmittel konnte nicht freigemeldet werden.");setNotice("Sanitätsmittel ist wieder frei für Einsätze.");setTimeout(()=>setNotice(""),3500);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Sanitätsmittel konnte nicht freigemeldet werden.")}finally{setBusy(false)}}
 async function assign(helperId:string,assignmentId:string){setData(current=>current?{...current,helpers:current.helpers.map(person=>person.id===helperId?{...person,assignmentId:assignmentId||null}:person)}:current);const response=await fetch(`/api/events/${encodeURIComponent(eventId)}/helpers/${encodeURIComponent(helperId)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({assignmentId:assignmentId||null})});if(!response.ok){setError("Einteilung konnte nicht gespeichert werden.");await load()}}
 async function downloadHelperPdf(){setPdfBusy(true);setError("");try{const response=await fetch(`/api/events/${encodeURIComponent(eventId)}/helpers/pdf`,{cache:"no-store"});if(!response.ok){const result=await response.json() as {error?:string};throw new Error(result.error||"PDF konnte nicht erstellt werden.")}const blob=await response.blob(),url=URL.createObjectURL(blob),disposition=response.headers.get("content-disposition")||"",match=disposition.match(/filename="([^"]+)"/),link=document.createElement("a");link.href=url;link.download=match?.[1]||"rescueed-helferliste.pdf";document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setNotice("Helferliste wurde als PDF erstellt.");setTimeout(()=>setNotice(""),3500)}catch(reason){setError(reason instanceof Error?reason.message:"PDF konnte nicht erstellt werden.")}finally{setPdfBusy(false)}}
 function qrUrl(kind:"come"|"leave",download=false){return `/api/events/${encodeURIComponent(eventId)}/qr?kind=${kind}${download?"&download=1":""}`}
 async function printQrCodes(kinds:Array<"come"|"leave">){setError("");const printWindow=window.open("","_blank","width=850,height=1100");if(!printWindow){setError("Druckfenster wurde blockiert. Bitte Pop-ups für diese Seite erlauben.");return}printWindow.document.title=`QR-Codes – ${data?.event.name||"RescueEd Alert"}`;printWindow.document.body.textContent="QR-Codes werden vorbereitet …";const urls:string[]=[];try{const images=await Promise.all(kinds.map(async kind=>{const response=await fetch(qrUrl(kind),{cache:"no-store"});if(!response.ok)throw new Error(`QR-Code ${kind==="come"?"Kommen":"Gehen"} konnte nicht geladen werden.`);const url=URL.createObjectURL(await response.blob());urls.push(url);return {kind,url}}));const doc=printWindow.document;doc.body.replaceChildren();const style=doc.createElement("style");style.textContent="@page{size:A4 portrait;margin:16mm}body{font:16px Arial,sans-serif;color:#10223d;margin:0}h1{font-size:24px;margin:0 0 5mm}p{color:#475569;margin:0 0 9mm}.codes{display:grid;gap:8mm}.code{border:1px solid #cbd5e1;border-radius:8px;padding:7mm;text-align:center;break-inside:avoid}.code h2{font-size:20px;margin:0 0 4mm}.code img{display:block;width:70mm;height:70mm;margin:0 auto 4mm}.code small{color:#475569}footer{margin-top:8mm;font-size:11px;color:#64748b}";doc.head.appendChild(style);const title=doc.createElement("h1");title.textContent=data?.event.name||"RescueEd Alert";doc.body.appendChild(title);const intro=doc.createElement("p");intro.textContent=`Anwesenheit · ${fmtDate(data?.event.eventDate||"")}`;doc.body.appendChild(intro);const grid=doc.createElement("div");grid.className="codes";const loaded:Promise<void>[]=[];for(const item of images){const section=doc.createElement("section"),heading=doc.createElement("h2"),image=doc.createElement("img"),hint=doc.createElement("small");section.className="code";heading.textContent=item.kind==="come"?"KOMMEN – Einchecken":"GEHEN – Auschecken";image.alt=`QR-Code ${item.kind==="come"?"Kommen":"Gehen"}`;image.src=item.url;hint.textContent=item.kind==="come"?"Diesen Code beim Dienstbeginn scannen.":"Diesen Code beim Dienstende scannen.";section.appendChild(heading);section.appendChild(image);section.appendChild(hint);grid.appendChild(section);loaded.push(image.decode())}doc.body.appendChild(grid);const footer=doc.createElement("footer");footer.textContent="RescueEd Alert · QR-Codes nur für dieses Event verwenden.";doc.body.appendChild(footer);await Promise.all(loaded);printWindow.focus();printWindow.print();printWindow.addEventListener("beforeunload",()=>urls.forEach(URL.revokeObjectURL),{once:true})}catch(reason){urls.forEach(URL.revokeObjectURL);printWindow.close();setError(reason instanceof Error?reason.message:"QR-Codes konnten nicht gedruckt werden.")}}
 async function sendAlarm(){setBusy(true);setError("");try{const response=await fetch(`/api/events/${encodeURIComponent(eventId)}/alerts`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({assignmentIds:selected,message})}),result=await response.json() as {error?:string;alert?:{createdAt:string}};if(!response.ok)throw new Error(result.error||"Alarmierung konnte nicht protokolliert werden.");const unitNames=data?.assignments.filter(unit=>selected.includes(unit.id)).map(unit=>unit.name)||[],payload={type:"alert",message,units:unitNames,eventId,at:result.alert?.createdAt||new Date().toISOString()};localStorage.setItem("rescueed-realtime",JSON.stringify(payload));const channel=new BroadcastChannel("rescueed-alert");channel.postMessage(payload);channel.close();setDialog(null);setMessage("");setSelected([]);await load();setNotice(`Alarm an ${unitNames.length} Sanitätsmittel um ${fmtTime(payload.at)} Uhr protokolliert.`);setTimeout(()=>setNotice(""),3500)}catch(reason){setError(reason instanceof Error?reason.message:"Alarmierung konnte nicht protokolliert werden.")}finally{setBusy(false)}}
 async function deleteEvent(){setBusy(true);setError("");try{const response=await fetch(`/api/events/${encodeURIComponent(eventId)}`,{method:"DELETE",headers:{"content-type":"application/json"},body:"{}"}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Event konnte nicht gelöscht werden.");setDeleted(true);setDialog("deleted")}catch(reason){setError(reason instanceof Error?reason.message:"Event konnte nicht gelöscht werden.");setDialog("details")}finally{setBusy(false)}}
 if(error&&!data)return <main className="event-dashboard"><header><Brand/><button className="ghost" onClick={home}><House/> Home</button></header><div className="dashboard-error">{error}<button onClick={load}>Erneut laden</button></div></main>;
 if(!data)return <main className="event-dashboard"><header><Brand/></header><div className="dashboard-loading">Event wird geladen …</div></main>;
 const unitName=(id:string|null)=>data.assignments.find(unit=>unit.id===id)?.name||"Nicht eingeteilt";
 return <main className="event-dashboard">
  <header className="screen-only"><Brand/><div><button className="ghost" onClick={home}><House size={17}/> Home</button><button className="ghost" onClick={logout}><LogOut size={17}/> Abmelden</button></div></header>
  <section className="event-summary screen-only"><div><p><i/>Dienst {data.event.status==="active"?"aktiv":data.event.status} · {fmtDate(data.event.eventDate)}{data.event.startTime&&data.event.endTime?` ${data.event.startTime} Uhr – ${fmtDate(data.event.endDate)} ${data.event.endTime} Uhr`:""}</p><h1>{data.event.name}</h1><span>{present.length} Helfer anwesend · {assigned} eingeteilt · {present.length-assigned} offen</span></div><div className="event-actions"><button className="secondary" onClick={()=>setDialog("details")}><FileText/> Details</button><button className="secondary" onClick={()=>setDialog("qr")}><QrCode/> QR Kommen / Gehen</button><button className="secondary" onClick={()=>setDialog("unit")}><Plus/> Sanitätsmittel</button><button className="danger" disabled={!present.length||!data.assignments.length} onClick={()=>setDialog("alert")}><BellRing/> Alarmieren</button></div></section>
  {notice&&<div className="dashboard-notice screen-only"><Check/>{notice}</div>}
  <div className="dashboard-grid"><section className="card helper-print-area"><header className="helper-head"><div><h2>Helfer</h2><p>Alphabetisch nach Nachname · aktuell anwesend und eingeteilt</p></div><div><span><Users/>{present.length}</span><button className="screen-only" onClick={()=>setDialog("helper")}><UserPlus/> Helfer anlegen</button><button className="screen-only" disabled={pdfBusy} onClick={downloadHelperPdf}><FileDown/> {pdfBusy?"PDF wird erstellt …":"Als PDF herunterladen"}</button></div></header><div className="print-title"><b>RescueEd Alert - Helferliste</b><h1>{data.event.name}</h1><p>{fmtDate(data.event.eventDate)} – {fmtDate(data.event.endDate)} · Eventnummer {data.event.id}</p></div>{present.length?<div className="helper-table"><div className="helper-row helper-labels"><span>Helfer / Qualifikation</span><span>Anwesenheit</span><span>Sanitätsmittel / Aktion</span></div>{present.map(person=><div className="helper-row" key={person.id}><div className="helper-person"><div className="avatar">{(person.firstName?.[0]||person.name[0])+(person.lastName?.[0]||"")}</div><div><b>{displayName(person)}</b><span>{person.qualification}</span></div></div><div className="attendance-times"><span><b>Kommen</b>{fmtTime(person.registeredAt)}</span><span><b>Gehen</b>-</span></div><div className="helper-management screen-only"><label className="select"><select aria-label={`Sanitätsmittel für ${person.name}`} value={person.assignmentId||""} onChange={event=>assign(person.id,event.target.value)}><option value="">Nicht eingeteilt</option>{data.assignments.map(unit=><option value={unit.id} key={unit.id}>{unit.name}</option>)}</select><ChevronDown/></label><button className="checkout-helper" disabled={busy} aria-label={`${person.name} ausbuchen`} title="Helfer ausbuchen" onClick={()=>checkoutHelper(person.id)}><UserMinus/></button></div><span className="print-unit">{unitName(person.assignmentId)}</span></div>)}</div>:<div className="empty-state"><Users/><b>Aktuell keine Helfer anwesend</b><p>Ausgecheckte Helfer bleiben im vollständigen Verlauf unter „Details“ erhalten.</p><button className="primary screen-only" onClick={()=>setDialog("helper")}><UserPlus/> Ersten Helfer anlegen</button></div>}</section>
   <section className="card resources-card screen-only"><header><div><h2>Sanitätsmittel</h2><p>{availableUnits.length} verfügbar · {deployedUnits.length} im Einsatz</p></div><button onClick={()=>setDialog("unit")}><Plus/> Anlegen</button></header>{data.assignments.length?<div className="resource-groups"><section className="resource-status-group"><h3>Verfügbar <span>{availableUnits.length}</span></h3>{availableUnits.length?<div className="resource-grid">{availableUnits.map(unit=>{const people=present.filter(person=>person.assignmentId===unit.id);return <article key={unit.id}><div className="resource-top"><ShieldCheck/><span>{people.length} Helfer</span>{!people.length&&<button className="resource-delete" aria-label={`${unit.name} löschen`} title="Sanitätsmittel löschen" onClick={()=>{setUnitToDelete(unit);setDialog("unit-delete")}}><Trash2/></button>}</div><h3>{unit.name}</h3>{people.length?people.map(person=><p key={person.id}>{displayName(person)} <small>{person.qualification}</small></p>):<p className="muted">Noch nicht besetzt</p>}<button disabled={!people.length} onClick={()=>{setSelected([unit.id]);setDialog("alert")}}><BellRing/> Alarmieren</button></article>})}</div>:<p className="resource-group-empty">Alle Sanitätsmittel befinden sich aktuell im Einsatz.</p>}</section><section className="resource-status-group deployed"><h3>Im Einsatz <span>{deployedUnits.length}</span></h3>{deployedUnits.length?<div className="resource-grid">{deployedUnits.map(unit=>{const people=present.filter(person=>person.assignmentId===unit.id);return <article className="resource-deployed" key={unit.id}><div className="resource-top"><BellRing/><span>Seit {fmtTime(unit.deployedAt)} Uhr</span></div><h3>{unit.name}</h3>{people.map(person=><p key={person.id}>{displayName(person)} <small>{person.qualification}</small></p>)}<button className="clear-unit" disabled={busy} onClick={()=>clearUnit(unit.id)}><Check/> Wieder frei für Einsätze</button></article>})}</div>:<p className="resource-group-empty">Aktuell ist kein Sanitätsmittel im Einsatz.</p>}</section></div>:<div className="empty-state compact"><ShieldCheck/><b>Noch keine Sanitätsmittel</b><p>Lege Fahrzeuge, Fußtrupps oder Stationen an. Danach stehen sie in der Helfer-Auswahl bereit.</p><button className="primary" onClick={()=>setDialog("unit")}><Plus/> Erstes Sanitätsmittel anlegen</button></div>}</section>
  </div>
  {dialog&&<div className="backdrop screen-only" onMouseDown={()=>dialog==="deleted"?undefined:setDialog(null)}><section className={`modal ${dialog==="details"||dialog==="qr"?"wide":""}`} role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}>{dialog!=="deleted"&&<button className="close" aria-label="Schließen" onClick={()=>setDialog(null)}><X/></button>}
   {dialog==="details"&&<><div className="bigicon"><FileText/></div><h2>Eventdetails</h2><div className="detail-grid"><div><span>Eventnummer</span><b>{data.event.id}</b></div><div><span>Bestellt am</span><b>{fmtDate(data.event.createdAt)}</b></div><div><span>Event</span><b>{fmtDate(data.event.eventDate)} {data.event.startTime||"–"} Uhr – {fmtDate(data.event.endDate)} {data.event.endTime||"–"} Uhr</b></div><div><span>Gebucht</span><b>Bis {data.event.helperLimit} Helfer · {(data.event.priceCents/100).toFixed(2).replace(".",",")} €</b></div></div><h3>Rechnungsdaten</h3>{data.invoice?<address><b>{data.invoice.recipientName}</b><span>{data.invoice.street}</span><span>{data.invoice.postalCode} {data.invoice.city}</span><span>{data.invoice.email}</span></address>:<p className="copy">Keine Rechnungsdaten vorhanden.</p>}<h3>Vollständiger Helferverlauf</h3>{data.helpers.length?<div className="detail-attendance">{data.helpers.map(person=><div key={person.id}><span><b>{displayName(person)}</b><small>{person.qualification} · {person.assignmentName||unitName(person.assignmentId)}</small></span><span>Kommen <b>{fmtTime(person.registeredAt)}</b></span><span>Gehen <b>{fmtTime(person.removedAt)}</b></span></div>)}</div>:<p className="copy">Noch keine Helfer eingecheckt.</p>}<div className="delete-zone"><div><b>Event löschen</b><span>Vor der endgültigen Löschung wird der vollständige Verlauf als PDF per E-Mail bereitgestellt.</span></div><button className="danger" onClick={()=>setDialog("delete")}><Trash2/> Event löschen</button></div></>}
   {dialog==="delete"&&<><div className="warningicon"><AlertTriangle/></div><h2>Event endgültig löschen?</h2><p className="copy">Diese Aktion kann nicht rückgängig gemacht werden. Event, Helfer, Anwesenheitszeiten, Sanitätsmittel und Alarmdaten werden gelöscht. Vorher wird eine Abschluss-PDF erzeugt und an die Rechnungs-E-Mail in den Ausgang gelegt.</p><div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>setDialog("details")}>Abbrechen</button><button className="danger" disabled={busy} onClick={deleteEvent}><Trash2/>{busy?"PDF wird erstellt …":"Endgültig löschen"}</button></div></>}
   {dialog==="deleted"&&<><div className="successicon"><MailCheck/></div><h2>Event wurde gelöscht</h2><p className="copy">Die Details kommen per E-Mail.</p><button className="primary full" onClick={home}>OK</button></>}
   {dialog==="qr"&&<><div className="bigicon"><QrCode/></div><h2>QR-Codes für Anwesenheit</h2><p className="copy">„Kommen“ erfasst Name und Qualifikation mit Uhrzeit. „Gehen“ beendet die Anwesenheit auf demselben Gerät.</p><div className="qr-grid"><article><span className="qr-status come">KOMMEN</span><img alt="QR-Code Kommen" src={qrUrl("come")}/><div className="qr-card-actions"><a href={qrUrl("come",true)} download><Download/> SVG herunterladen</a><button onClick={()=>printQrCodes(["come"])}><Printer/> Drucken</button><button onClick={()=>navigator.clipboard?.writeText(data.attendanceLinks.come)}><Copy/> Link kopieren</button></div></article><article><span className="qr-status leave">GEHEN</span><img alt="QR-Code Gehen" src={qrUrl("leave")}/><div className="qr-card-actions"><a href={qrUrl("leave",true)} download><Download/> SVG herunterladen</a><button onClick={()=>printQrCodes(["leave"])}><Printer/> Drucken</button><button onClick={()=>navigator.clipboard?.writeText(data.attendanceLinks.leave)}><Copy/> Link kopieren</button></div></article></div><button className="secondary qr-print-all" onClick={()=>printQrCodes(["come","leave"])}><Printer/> Beide QR-Codes drucken</button><p className="copy qr-print-hint">Im Druckdialog kannst du die QR-Codes auch als PDF speichern.</p>{error&&<p className="copy modal-error" role="alert">{error}</p>}</>}
   {dialog==="unit"&&<><div className="bigicon"><ShieldCheck/></div><h2>Sanitätsmittel anlegen</h2><p className="copy">Zum Beispiel RTW 1, KTW 2, Fußtrupp Nord oder Unfallhilfsstelle.</p><label className="field">Bezeichnung<input autoFocus maxLength={80} value={newUnit} onChange={event=>setNewUnit(event.target.value)} placeholder="z. B. RTW 1"/></label><button className="primary full" disabled={busy||!newUnit.trim()} onClick={addUnit}>{busy?"Wird gespeichert …":"Sanitätsmittel anlegen"}</button></>}
   {dialog==="unit-delete"&&unitToDelete&&<><div className="warningicon"><AlertTriangle/></div><h2>Sanitätsmittel löschen?</h2><p className="copy"><b>{unitToDelete.name}</b> ist aktuell nicht besetzt und wird aus diesem Event entfernt.</p><div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>setDialog(null)}>Abbrechen</button><button className="danger" disabled={busy} onClick={deleteUnit}><Trash2/>{busy?"Wird gelöscht …":"Sanitätsmittel löschen"}</button></div></>}
   {dialog==="helper"&&<><div className="bigicon"><UserPlus/></div><h2>Helfer anlegen</h2><p className="copy">Der Helfer wird sofort mit der aktuellen Uhrzeit als anwesend erfasst.</p><label className="field">Vorname<input autoFocus maxLength={80} value={newHelper.firstName} onChange={event=>setNewHelper(current=>({...current,firstName:event.target.value}))}/></label><label className="field">Nachname<input maxLength={80} value={newHelper.lastName} onChange={event=>setNewHelper(current=>({...current,lastName:event.target.value}))}/></label><label className="field">Qualifikation<input maxLength={100} value={newHelper.qualification} onChange={event=>setNewHelper(current=>({...current,qualification:event.target.value}))} placeholder="z. B. Rettungssanitäter/in"/></label>{error&&<p className="copy modal-error" role="alert">{error}</p>}<button className="primary full" disabled={busy||!newHelper.firstName.trim()||!newHelper.lastName.trim()||!newHelper.qualification.trim()} onClick={addHelper}>{busy?"Wird angelegt …":"Helfer anlegen"}</button></>}
   {dialog==="alert"&&<><div className="alarmicon"><BellRing/></div><h2>Alarm senden</h2><p className="copy">Wähle die Sanitätsmittel aus, deren anwesende Helfer alarmiert werden.</p><div className="checks">{availableUnits.map(unit=><label key={unit.id}><input type="checkbox" checked={selected.includes(unit.id)} onChange={()=>setSelected(current=>current.includes(unit.id)?current.filter(id=>id!==unit.id):[...current,unit.id])}/><b>{unit.name}</b><span>{present.filter(person=>person.assignmentId===unit.id).length}</span></label>)}</div><label className="field">Kurze Meldung <em>optional</em><textarea maxLength={150} value={message} onChange={event=>setMessage(event.target.value)}/></label><button className="danger full" disabled={busy||!selected.length} onClick={sendAlarm}><BellRing/> {busy?"Wird alarmiert …":"Alarm senden"}</button></>}
  </section></div>}
 </main>
}
