"use client";
import "./flows.css";
import "./welcome-footer.css";
import "./welcome-dialog.css";
import {useState,type ReactNode} from "react";
import {ArrowRight,BellRing,CalendarDays,Check,FileText,LockKeyhole,LogOut,Mail,Plus,Radio,ShieldCheck,Users} from "lucide-react";
import {RescueEdLogo} from "@/components/brand-logo";

function Brand(){return <div className="flex items-center gap-3"><RescueEdLogo/><div><b>RescueEd Alert</b><p>Einchecken · Einteilen · Alarmieren</p></div></div>}
function UnitIcon(){return <div className="icon"><ShieldCheck size={18}/></div>}

export function NewWelcome({login,register}:{login:()=>void;register:()=>void}){
 const [legal,setLegal]=useState<{title:string;version:string;content:string;status:string}|null>(null),[loading,setLoading]=useState("");
 async function openLegal(slug:"impressum"|"datenschutz"){setLoading(slug);try{const response=await fetch(`/api/legal-documents/${slug}`),document=await response.json() as {title:string;version:string;content:string;status:string};if(response.ok)setLegal(document)}finally{setLoading("")}}
 return <main className="welcome"><nav><Brand/><div className="flex gap-2"><button className="navregister" onClick={register}>Registrieren</button><button className="navlogin" onClick={login}>Anmelden</button></div></nav><section className="welcomegrid"><div><span className="eyebrow"><i/> Alarmierung für Sanitätsdienste</span><h1>Willkommen bei<br/><strong>RescueEd Alert</strong></h1><p className="lead">Events anlegen, Helfer einteilen und gezielt alarmieren. Klar organisiert auf jedem Gerät.</p><div className="flex flex-wrap gap-3"><button className="start" onClick={register}>Kostenlos registrieren <ArrowRight size={20}/></button><button className="start secondarystart" onClick={login}>Zum Login</button></div><div className="promise"><span><Check/>Web, Android & iOS</span><span><Check/>Ab 5,99 € je Event</span><span><Check/>Abrechnung per Rechnung</span></div></div><div className="signalcard"><div className="signalhead"><div className="signalicon"><BellRing/></div><span>RescueEd Alert</span><i>LIVE</i></div><div className="signalbody"><small>AKTIVER SANITÄTSDIENST</small><h2>Stadtfest Musterstadt</h2><p>8 Helfer angemeldet</p><div className="signalunit"><UnitIcon/><div><b>Fußtrupp 2</b><span>2 Helfer einsatzbereit</span></div><em><Radio size={16}/> alarmierbar</em></div><div className="flow"><span><b>1</b>Einchecken</span><i/><span><b>2</b>Einteilen</span><i/><span><b>3</b>Alarmieren</span></div></div></div></section><footer className="welcomefooter"><div><button disabled={loading==="impressum"} onClick={()=>openLegal("impressum")}>Impressum</button><button disabled={loading==="datenschutz"} onClick={()=>openLegal("datenschutz")}>Datenschutz (DSGVO)</button></div><p>© 2026 RescueEd · b.peinzger · Alle Rechte vorbehalten</p></footer>{legal&&<div className="legaloverlay" role="presentation" onMouseDown={()=>setLegal(null)}><section className="legalmodal" role="dialog" aria-modal="true" aria-labelledby="legal-title" onMouseDown={event=>event.stopPropagation()}><header><div><span>{legal.status==="published"?"Veröffentlicht":"Entwurf – rechtlich prüfen"}</span><h2 id="legal-title">{legal.title}</h2><small>Version {legal.version}</small></div></header><div className="legalmodalcontent">{legal.content.split("\n").map((line,index)=>line?<p key={index}>{line}</p>:<br key={index}/>)}</div><footer><button autoFocus onClick={()=>setLegal(null)}>OK</button></footer></section></div>}</main>
}

export function NewLogin({back,submit,register}:{back:()=>void;submit:()=>void;register:()=>void}){const [email,setEmail]=useState(""),[password,setPassword]=useState("");return <AuthShell back={back} title="Willkommen zurück" copy="Melde dich an, um deine Events zu verwalten."><form className="authform" autoComplete="off" onSubmit={e=>{e.preventDefault();submit()}}><AuthInput label="E-Mail-Adresse" icon={<Mail/>}><input required type="email" autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)}/></AuthInput><AuthInput label="Passwort" icon={<LockKeyhole/>}><input required type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Passwort eingeben"/></AuthInput><button type="submit">Anmelden <ArrowRight size={18}/></button></form><button className="textlink" onClick={register}>Noch kein Konto? Jetzt registrieren</button></AuthShell>}

export function Register({back,submit}:{back:()=>void;submit:()=>void}){return <AuthShell back={back} title="Konto erstellen" copy="Registriere dich als verantwortliche Person."><form className="authform" onSubmit={e=>{e.preventDefault();submit()}}><AuthInput label="Vor- und Nachname" icon={<Users/>}><input required placeholder="Max Mustermann"/></AuthInput><AuthInput label="Organisation" icon={<ShieldCheck/>}><input required placeholder="Hilfsorganisation"/></AuthInput><AuthInput label="E-Mail-Adresse" icon={<Mail/>}><input required type="email" placeholder="name@organisation.de"/></AuthInput><AuthInput label="Passwort" icon={<LockKeyhole/>}><input required type="password" placeholder="Mindestens 8 Zeichen"/></AuthInput><button type="submit">Konto erstellen <ArrowRight size={18}/></button></form><button className="textlink" onClick={back}>Bereits registriert? Zum Login</button></AuthShell>}

function AuthShell({back,title,copy,children}:{back:()=>void;title:string;copy:string;children:ReactNode}){return <main className="loginpage"><button className="backhome" onClick={back}>← Zurück</button><section className="loginbox"><div className="loginbrand"><RescueEdLogo className="brand-logo--auth"/><h1>RescueEd Alert</h1><p>Einchecken · Einteilen · Alarmieren</p></div><div className="loginform"><h2>{title}</h2><p>{copy}</p>{children}</div></section></main>}
function AuthInput({label,icon,children}:{label:string;icon:ReactNode;children:ReactNode}){return <label>{label}<div>{icon}{children}</div></label>}

export function Events({open,create,logout}:{open:()=>void;create:()=>void;logout:()=>void}){return <main className="portal"><header><Brand/><button className="portal-logout" onClick={logout}><LogOut size={17}/> Abmelden</button></header><section className="portalbody"><div className="portal-title"><div><p>EVENTVERWALTUNG</p><h1>Deine Events</h1><span>Wähle ein Event aus oder erstelle einen neuen Sanitätsdienst.</span></div><button onClick={create}><Plus/> Neues Event</button></div><div className="eventgrid"><button className="eventcard" onClick={open}><div className="eventdate"><b>14</b><span>SEP</span></div><div><span className="activebadge">Aktiv</span><h2>Stadtfest Musterstadt</h2><p><Users size={16}/> 8 Helfer · 6 eingeteilt</p></div><ArrowRight className="eventarrow"/></button><button className="newevent" onClick={create}><Plus/><b>Neues Event erstellen</b><span>Sanitätsdienst anlegen und Helfer einladen</span></button></div></section></main>}

export function CreateEvent({back,done}:{back:()=>void;done:()=>void}){const [count,setCount]=useState(20),price=count<=20?"5,99 €":"9,99 €";return <main className="formpage"><header><Brand/><button onClick={back}>Abbrechen</button></header><section className="createwrap"><div className="steps"><span className="current">1</span><i/><span>2</span><i/><span>3</span></div><div className="createhead"><p>NEUES EVENT</p><h1>Sanitätsdienst erstellen</h1><span>Nach dem Speichern werden die Rechnungsdaten an RescueEd übermittelt.</span></div><form className="createform" onSubmit={e=>{e.preventDefault();done()}}><div><section><h2><CalendarDays/> Eventdetails</h2><label>Name des Events<input required defaultValue="Stadtfest Musterstadt"/></label><div className="twocol"><label>Datum<input required type="date" defaultValue="2026-09-14"/></label><label>Voraussichtliche Helferzahl<input required type="number" min="1" value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div></section><section><h2><FileText/> Rechnungsdaten</h2><label>Organisation / Rechnungsempfänger<input required placeholder="Organisation"/></label><div className="twocol"><label>Straße und Hausnummer<input required placeholder="Musterstraße 1"/></label><label>PLZ und Ort<input required placeholder="12345 Musterstadt"/></label></div><label>Rechnungs-E-Mail<input required type="email" defaultValue="rechnung@organisation.de"/></label></section></div><aside className="pricebox"><div><span>Event bis {count} Helfer</span><b>{price}</b></div><p>Einmaliger Preis pro Event · Rechnung wird durch RescueEd erstellt.</p><ul><li><Check/> QR-Check-in</li><li><Check/> Einteilung & Alarmierung</li><li><Check/> App-Anbindung vorbereitet</li></ul><button type="submit">Zahlungspflichtig erstellen · {price}</button><small>Es erfolgt keine automatische Abbuchung. Die Rechnungsdaten werden zur manuellen Bearbeitung vorgemerkt.</small></aside></form></section></main>}
