import {effectiveEventEndDate} from "./event-duration";

type HelperListInput={event:{id:string;name:string;eventDate:string;endDate?:string|null;startTime:string|null;endTime:string|null};helpers:Array<{firstName:string|null;lastName:string|null;name:string;qualification:string;registeredAt:Date|string;assignmentName:string|null}>;generatedAt?:Date};
const PAGE_W=595,PAGE_H=842,MARGIN=42;
const BLUE=[0.04,0.16,0.29] as const,ACCENT=[0.08,0.42,0.91] as const,INK=[0.08,0.13,0.22] as const,MUTED=[0.38,0.45,0.55] as const,LIGHT=[0.93,0.96,0.99] as const;
function safe(value:unknown){return String(value??"").replace(/[äÄ]/g,"ae").replace(/[öÖ]/g,"oe").replace(/[üÜ]/g,"ue").replace(/ß/g,"ss").replace(/[–—]/g,"-").replace(/[^ -~]/g," ").replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)")}
function date(value:Date|string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeZone:"Europe/Berlin"}).format(new Date(value))}
function time(value:Date|string){return new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Berlin"}).format(new Date(value))}
function wrap(value:string,max:number){const words=safe(value).split(/\s+/),lines:string[]=[];let current="";for(const word of words){const next=current?`${current} ${word}`:word;if(next.length>max&&current){lines.push(current);current=word}else current=next}if(current)lines.push(current);return lines.length?lines:[""]}
function text(value:string,x:number,y:number,size=10,bold=false,color:readonly number[]=INK){return `BT /F${bold?2:1} ${size} Tf ${color[0]} ${color[1]} ${color[2]} rg 1 0 0 1 ${x} ${y} Tm (${safe(value)}) Tj ET`}
function rect(x:number,y:number,w:number,h:number,color:readonly number[]){return `${color[0]} ${color[1]} ${color[2]} rg ${x} ${y} ${w} ${h} re f`}
function line(x1:number,y1:number,x2:number,y2:number,color:readonly number[]=[.82,.87,.92]){return `${color[0]} ${color[1]} ${color[2]} RG .6 w ${x1} ${y1} m ${x2} ${y2} l S`}
export function createHelperListPdf(input:HelperListInput){
 const pages:string[][]=[];let page:string[]=[],y=PAGE_H-MARGIN;
 const newPage=()=>{if(page.length)pages.push(page);page=[];y=PAGE_H-MARGIN;const titleSize=Math.max(11,Math.min(18,510/Math.max(1,safe(input.event.name).length*.55)));page.push(rect(0,PAGE_H-92,PAGE_W,92,BLUE),text(input.event.name,MARGIN,PAGE_H-48,titleSize,true,[1,1,1]),text("Helferliste - aktuell anwesend",MARGIN,PAGE_H-70,9,false,[.72,.84,.98]));y=PAGE_H-122};
 const cols=[MARGIN,MARGIN+170,MARGIN+330,MARGIN+405],widths=[166,156,71,148];
 const header=()=>{page.push(rect(MARGIN,y-23,PAGE_W-MARGIN*2,28,BLUE));["Helfer","Qualifikation","Kommen","Sanitaetsmittel"].forEach((value,index)=>page.push(text(value,cols[index]+5,y-13,7,true,[1,1,1])));y-=30};
 newPage();page.push(text(`Eventnummer: ${input.event.id}`,MARGIN,y,8,false,MUTED));y-=18;page.push(text(`Event: ${date(input.event.eventDate)} ${input.event.startTime||"-"} bis ${date(effectiveEventEndDate(input.event.eventDate,input.event.startTime,input.event.endDate,input.event.endTime))} ${input.event.endTime||"-"} Uhr`,MARGIN,y,9,true,INK));y-=18;page.push(text(`Erstellt am ${date(input.generatedAt||new Date())} | ${input.helpers.length} Helfer anwesend`,MARGIN,y,8,false,MUTED));y-=32;header();
 if(!input.helpers.length){page.push(text("Aktuell keine Helfer anwesend.",MARGIN+7,y-15,9));y-=34}
 for(const helper of input.helpers){const helperName=helper.lastName?`${helper.lastName}, ${helper.firstName||""}`:helper.name,cells=[helperName,helper.qualification,time(helper.registeredAt),helper.assignmentName||"Nicht eingeteilt"],wrapped=cells.map((cell,index)=>wrap(cell,Math.max(8,Math.floor(widths[index]/5.5)))),height=Math.max(34,wrapped.reduce((maximum,cell)=>Math.max(maximum,cell.length),1)*10+14);if(y-height<58){newPage();page.push(text("Helferliste - Fortsetzung",MARGIN,y,10,true,ACCENT));y-=28;header()}page.push(rect(MARGIN,y-height+4,PAGE_W-MARGIN*2,height,y%2?LIGHT:[1,1,1]));wrapped.forEach((cell,index)=>cell.forEach((value,row)=>page.push(text(value,cols[index]+5,y-11-row*10,7.5,index===0,INK))));for(let index=1;index<cols.length;index++)page.push(line(cols[index],y+4,cols[index],y-height+4));page.push(line(MARGIN,y-height+4,PAGE_W-MARGIN,y-height+4));y-=height}
 pages.push(page);pages.forEach((commands,index)=>commands.push(line(MARGIN,42,PAGE_W-MARGIN,42),text("RescueEd - Email: info@rescueed.de - Telefon: /49 3601/ 80 80 191",MARGIN,26,7,false,MUTED),text(`Seite ${index+1} von ${pages.length}`,PAGE_W-MARGIN-62,26,7,false,MUTED)));
 const objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>","","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"],kids:number[]=[];for(const commands of pages){const pageId=objects.length+1,contentId=pageId+1;kids.push(pageId);objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`);const content=commands.join("\n");objects.push(`<< /Length ${new TextEncoder().encode(content).length} >>\nstream\n${content}\nendstream`)}objects[1]=`<< /Type /Pages /Kids [${kids.map(identifier=>`${identifier} 0 R`).join(" ")}] /Count ${kids.length} >>`;
 let pdf="%PDF-1.4\n%RescueEd\n";const offsets=[0];objects.forEach((object,index)=>{offsets.push(new TextEncoder().encode(pdf).length);pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=new TextEncoder().encode(pdf).length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(pdf)
}
