export const LEGAL_VERSIONS={terms:"2026-09-15",privacy:"2026-09-15",avv:"2026-09-15"} as const;

export const legalDocumentDefaults={
 agb:{title:"Allgemeine Geschäftsbedingungen (AGB)",version:LEGAL_VERSIONS.terms,content:"Entwurf – vor Veröffentlichung rechtlich prüfen.\n\nDiese Bedingungen regeln die Nutzung von RescueEd Alert durch Organisationen und deren berechtigte Nutzer. Vertragsgegenstand ist die technische Unterstützung bei Check-in, Einteilung und Alarmierung innerhalb eines Sanitätsdienstes. Medizinische Dokumentation, Einsatzführung und Funkkommunikation bleiben außerhalb des Systems.\n\nPreise, Leistungsumfang, Laufzeit, Verfügbarkeit, Haftung und Kündigung richten sich nach dem jeweils gebuchten Event-Paket und der bestätigten Leistungsbeschreibung."},
 agb_b2c:{title:"Nutzungsbedingungen für private App-Abonnements",version:"2026-09-17",content:"Entwurf – vor Veröffentlichung anwaltlich prüfen.\n\nDiese Fassung gilt ausschließlich für private Nutzer der RescueEd Alert App. Das monatliche Abonnement wird über Google Play oder den Apple App Store abgeschlossen und verwaltet. Der im jeweiligen Store vor Kaufabschluss angezeigte Preis und die dort angezeigten Bedingungen sind maßgeblich. Ein aktives, dem App-Konto zugeordnetes Abonnement ermöglicht das Anlegen neuer Events in der App. Nach Ablauf können bereits angelegte Events fortgeführt, aber keine neuen Events angelegt werden. Ein Zugang zum Organisations-SaaS ist damit nicht verbunden.\n\nLaufzeit, automatische Verlängerung, Kündigung, Erstattung, technische Verfügbarkeit und Haftung müssen vor Veröffentlichung vollständig und passend zum jeweiligen Store ergänzt werden."},
 datenschutz:{title:"Datenschutzerklärung",version:LEGAL_VERSIONS.privacy,content:"Entwurf – vor Veröffentlichung rechtlich prüfen.\n\nRescueEd Alert verarbeitet Konto-, Organisations-, Kontakt- und Abrechnungsdaten zur Bereitstellung der SaaS. Ereignisprotokolle im Unternehmerbereich werden auf Ersteller und Zeitpunkt begrenzt. Es werden keine Patientendaten für die Plattformfunktion benötigt.\n\nBetroffene Personen haben im Rahmen der gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Aufbewahrungs- und Löschfristen sind vor dem Produktivbetrieb verbindlich festzulegen."},
 impressum:{title:"Impressum",version:"2026-09-15",content:"Entwurf – Unternehmensangaben ergänzen und rechtlich prüfen.\n\nRescueEd Alert\nBetreiber: [vollständiger Name / Rechtsform]\nAnschrift: [Straße, Hausnummer, PLZ, Ort]\nE-Mail: kontakt@rescueed.de\nVertretungsberechtigt: [Name]\nRegister / Umsatzsteuer-ID: [falls vorhanden]"},
 avv:{title:"Auftragsverarbeitungsvertrag (AVV)",version:LEGAL_VERSIONS.avv,content:"Entwurf – vor Veröffentlichung rechtlich prüfen.\n\nDer AVV beschreibt Gegenstand und Dauer der Verarbeitung, Art und Zweck, Kategorien betroffener Personen und Daten sowie die Rechte und Pflichten von Auftraggeber und Auftragnehmer. Technische und organisatorische Maßnahmen, Unterauftragnehmer, Weisungen, Kontrollrechte, Löschung und Rückgabe sind vor dem Produktivbetrieb verbindlich zu ergänzen."},
 sla:{title:"Service Level Agreement (SLA)",version:"2026-09-15",content:"Entwurf – vor Veröffentlichung rechtlich und betrieblich prüfen.\n\nDas SLA legt Verfügbarkeit, Wartungsfenster, Supportzeiten, Reaktions- und Wiederherstellungsziele sowie Ausschlüsse fest. Alarmierung darf nicht als alleiniger Kommunikationsweg für lebenswichtige oder zeitkritische Maßnahmen verwendet werden; der vereinbarte Funk- und Einsatzführungsprozess bleibt maßgeblich."},
 widerruf:{title:"Widerrufsbelehrung für Verbraucher",version:"2026-09-17",content:"Entwurf – vor Veröffentlichung anwaltlich prüfen.\n\nFür online abgeschlossene B2C-Abonnements müssen Widerrufsrecht, Frist, Ausübung, Folgen und Muster-Widerrufsformular vollständig und passend zur Abwicklung über Google Play beziehungsweise den App Store beschrieben werden. Dieser Entwurf ist keine freigegebene Widerrufsbelehrung."}
} as const;

export type LegalDocumentKey=keyof typeof legalDocumentDefaults;
