export const LEGAL_VERSIONS={terms:"2026-09-15",privacy:"2026-09-15",avv:"2026-09-15"} as const;

export const legalDocumentDefaults={
 agb:{title:"Allgemeine Geschäftsbedingungen (AGB)",version:LEGAL_VERSIONS.terms,content:"Entwurf – vor Veröffentlichung rechtlich prüfen.\n\nDiese Bedingungen regeln die Nutzung von RescueEd Alert durch Organisationen und deren berechtigte Nutzer. Vertragsgegenstand ist die technische Unterstützung bei Check-in, Einteilung und Alarmierung innerhalb eines Sanitätsdienstes. Medizinische Dokumentation, Einsatzführung und Funkkommunikation bleiben außerhalb des Systems.\n\nPreise, Leistungsumfang, Laufzeit, Verfügbarkeit, Haftung und Kündigung richten sich nach dem jeweils gebuchten Event-Paket und der bestätigten Leistungsbeschreibung."},
 datenschutz:{title:"Datenschutzerklärung",version:LEGAL_VERSIONS.privacy,content:"Entwurf – vor Veröffentlichung rechtlich prüfen.\n\nRescueEd Alert verarbeitet Konto-, Organisations-, Kontakt- und Abrechnungsdaten zur Bereitstellung der SaaS. Ereignisprotokolle im Unternehmerbereich werden auf Ersteller und Zeitpunkt begrenzt. Es werden keine Patientendaten für die Plattformfunktion benötigt.\n\nBetroffene Personen haben im Rahmen der gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Aufbewahrungs- und Löschfristen sind vor dem Produktivbetrieb verbindlich festzulegen."},
 impressum:{title:"Impressum",version:"2026-09-15",content:"Entwurf – Unternehmensangaben ergänzen und rechtlich prüfen.\n\nRescueEd Alert\nBetreiber: [vollständiger Name / Rechtsform]\nAnschrift: [Straße, Hausnummer, PLZ, Ort]\nE-Mail: kontakt@rescueed.de\nVertretungsberechtigt: [Name]\nRegister / Umsatzsteuer-ID: [falls vorhanden]"},
 avv:{title:"Auftragsverarbeitungsvertrag (AVV)",version:LEGAL_VERSIONS.avv,content:"Entwurf – vor Veröffentlichung rechtlich prüfen.\n\nDer AVV beschreibt Gegenstand und Dauer der Verarbeitung, Art und Zweck, Kategorien betroffener Personen und Daten sowie die Rechte und Pflichten von Auftraggeber und Auftragnehmer. Technische und organisatorische Maßnahmen, Unterauftragnehmer, Weisungen, Kontrollrechte, Löschung und Rückgabe sind vor dem Produktivbetrieb verbindlich zu ergänzen."},
 sla:{title:"Service Level Agreement (SLA)",version:"2026-09-15",content:"Entwurf – vor Veröffentlichung rechtlich und betrieblich prüfen.\n\nDas SLA legt Verfügbarkeit, Wartungsfenster, Supportzeiten, Reaktions- und Wiederherstellungsziele sowie Ausschlüsse fest. Alarmierung darf nicht als alleiniger Kommunikationsweg für lebenswichtige oder zeitkritische Maßnahmen verwendet werden; der vereinbarte Funk- und Einsatzführungsprozess bleibt maßgeblich."}
} as const;

export type LegalDocumentKey=keyof typeof legalDocumentDefaults;
