"use client";
import {FormEvent,Suspense,useState} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {PasswordField} from "@/components/password-field";
import "../unternehmer/unternehmer.css";
import "../unternehmer/owner-enhancements.css";
export default function PasswordReset(){return <Suspense fallback={<main className="ownerlogin"/>}><PasswordResetForm/></Suspense>}
function PasswordResetForm(){const search=useSearchParams(),token=search.get("token")||"",registration=search.get("mode")==="registration",[password,setPassword]=useState(""),[repeat,setRepeat]=useState(""),[message,setMessage]=useState(""),[done,setDone]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(password!==repeat){setMessage("Die Passwörter stimmen nicht überein.");return}const r=await fetch("/api/password-reset",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,password})}),d=await r.json() as {type?:string;error?:string};if(r.ok){setDone(true);setMessage(d.type==="registration"?"Ihr Kundenkonto wurde angelegt. Sie können sich jetzt anmelden.":"Ihr Passwort wurde gespeichert. Sie können sich jetzt anmelden.")}else setMessage(d.error||"Der Link konnte nicht verarbeitet werden.")}return <main className="ownerlogin"><section><p>RESCUEED ALERT</p><h1>{registration?"Registrierung abschließen":"Passwort festlegen"}</h1>{registration&&<div className="loginmessage">Erst mit dem Speichern des Passworts wird Ihr Kundenkonto angelegt.</div>}{done?<><div className="loginmessage success">{message}</div><Link className="loginlink" href="/">Zur Anmeldung</Link></>:<form onSubmit={submit}><label>Neues Passwort<PasswordField minLength={12} autoComplete="new-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Passwort wiederholen<PasswordField minLength={12} autoComplete="new-password" required value={repeat} onChange={e=>setRepeat(e.target.value)}/></label><small>Mindestens 12 Zeichen. Verwenden Sie ein einzigartiges Passwort.</small><button disabled={!token}>Passwort sicher speichern</button>{message&&<div className="loginmessage">{message}</div>}</form>}</section></main>}
