"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import Link from "next/link";
type Ticket={id:string;subject:string;status:string;updatedAt:string};
type Message={id:string;authorType:string;body:string;createdAt:string};
export function SupportClient({name}:{name:string}){
 const [subject,setSubject]=useState(""),[message,setMessage]=useState(""),[reply,setReply]=useState(""),[tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<Ticket|null>(null),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch("/api/support/tickets",{cache:"no-store"}),d=await r.json() as {tickets?:Ticket[];error?:string};if(!r.ok)throw new Error(d.error);setTickets(d.tickets||[])}catch(e){setError(e instanceof Error?e.message:"Tickets konnten nicht geladen werden.")}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/support/tickets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({subject,message})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setSubject("");setMessage("");await load()}catch(e){setError(e instanceof Error?e.message:"Ticket konnte nicht erstellt werden.")}finally{setBusy(false)}}
 async function open(ticket:Ticket){setSelected(ticket);setMessages([]);try{const r=await fetch(`/api/support/tickets/${encodeURIComponent(ticket.id)}`,{cache:"no-store"}),d=await r.json() as {messages?:Message[];error?:string};if(!r.ok)throw new Error(d.error);setMessages(d.messages||[])}catch(e){setError(e instanceof Error?e.message:"Ticket konnte nicht geladen werden.")}}
 async function send(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError("");try{const r=await fetch(`/api/support/tickets/${encodeURIComponent(selected.id)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:reply})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setReply("");await open(selected);await load()}catch(e){setError(e instanceof Error?e.message:"Antwort konnte nicht gesendet werden.")}finally{setBusy(false)}}
 return <main className="customer-support"><header><div><small>RESCUEED ALERT</small><h1>Support & Tickets</h1><p>Hallo {name}. Beschreibe dein Anliegen ohne Passwörter, Sicherheitscodes oder Patientendaten.</p></div><Link href="/">← Zur Eventübersicht</Link></header><div className="customer-support-grid"><section><h2>Neues Ticket</h2><form onSubmit={create}><label>Betreff<input value={subject} onChange={e=>setSubject(e.target.value)} minLength={5} maxLength={120} required/></label><label>Beschreibung<textarea value={message} onChange={e=>setMessage(e.target.value)} minLength={15} maxLength={4000} rows={7} required/></label><button disabled={busy}>Ticket erstellen</button></form><h2>Meine Tickets</h2>{tickets.length?tickets.map(ticket=><button className="ticket-choice" key={ticket.id} onClick={()=>void open(ticket)}><b>{ticket.subject}</b><span>{ticket.status} · {new Date(ticket.updatedAt).toLocaleString("de-DE")}</span></button>):<p>Noch keine Tickets vorhanden.</p>}</section><section><h2>Verlauf</h2>{selected?<><h3>{selected.subject}</h3>{messages.map(item=><article key={item.id}><b>{item.authorType==="support"?"Support":"Du"}</b><small>{new Date(item.createdAt).toLocaleString("de-DE")}</small><p>{item.body}</p></article>)}{selected.status!=="resolved"&&<form onSubmit={send}><label>Antwort<textarea value={reply} onChange={e=>setReply(e.target.value)} minLength={2} maxLength={4000} rows={4} required/></label><button disabled={busy}>Antwort senden</button></form>}</>:<p>Wähle links ein Ticket aus.</p>}</section></div>{error&&<p className="support-error" role="alert">{error}</p>}</main>
}
