"use client";
import {FormEvent,useEffect,useMemo,useState,type ReactNode} from "react";
import Link from "next/link";
import {BookOpen,Building2,CalendarDays,Download,FileSpreadsheet,LayoutDashboard,Mail,Search,ScrollText,ShieldCheck,Users,X} from "lucide-react";
import {RescueEdLogo} from "@/components/brand-logo";
import {ComplimentaryAccessToggle,LogoutButton,PasswordLinkButton,UnlimitedEventDurationToggle,UserStatusButton} from "./actions";
type Area="uebersicht"|"kunden"|"rechnungen"|"emails"|"rechtliches"|"sicherheit";
type Customer={id:string;name:string;email:string;status:string;accountType:"organization"|"consumer";organization:string;complimentaryAccess:boolean;unlimitedEventDuration:boolean;createdAt:string;subscription:{store:"google"|"apple";status:string;expiresAt:string|null;lastVerifiedAt:string|null}|null};
type ArchivedCustomer={id:string;name:string;email:string;organization:string;deletedAt:string;retentionReviewAt:string;legalVersions:string;legalEvidence:Array<{documentKey:string;version:string;contentHash:string;acceptedAt:string;title:string|null;content:string|null}>};
type Booking={id:string;customer:string;organization:string;email:string;helperLimit:number;amount:number;currency:string;createdAt:string};
type LogRow={id:string;action:string;entityType:string;createdAt:string};
type EmailAction="mfa"|"registration_link"|"password_reset"|"customer_contact";
type LegalKey="agb"|"agb_b2c"|"datenschutz"|"impressum"|"avv"|"sla"|"widerruf";
type LegalDocument={documentKey:LegalKey;title:string;version:string;content:string;status:"draft"|"published"};
type LegalVersion={documentKey:LegalKey;title:string;version:string;content:string;contentHash:string;publishedAt:string;archivedAt:string|null};
const areas:{id:Area;label:string;icon:ReactNode}[]=[{id:"uebersicht",label:"Übersicht",icon:<LayoutDashboard/>},{id:"kunden",label:"Kundenverwaltung",icon:<Users/>},{id:"rechnungen",label:"Buchungen & Export",icon:<FileSpreadsheet/>},{id:"emails",label:"E-Mail-Einstellungen",icon:<Mail/>},{id:"rechtliches",label:"Rechtliches",icon:<BookOpen/>},{id:"sicherheit",label:"Sicherheit & Audit",icon:<ShieldCheck/>}];
const emailActions:{id:EmailAction;title:string;copy:string}[]=[{id:"mfa",title:"Sicherheitscode",copy:"Absender für Sicherheitscodes bei der Anmeldung."},{id:"registration_link",title:"Registrierungslink",copy:"Absender für die Einrichtung neuer Kundenkonten."},{id:"password_reset",title:"Passwort vergessen",copy:"Absender für Links zum Zurücksetzen des Passworts."},{id:"customer_contact",title:"Allgemeiner Kundenkontakt",copy:"Absender für Vertrags- und Serviceinformationen."}];
export function OwnerDashboard({operator,counts,customers,archivedCustomers,bookings,emailSettings,legalDocuments,legalVersions,logs}:{operator:{name:string;email:string};counts:{organizations:number;customers:number;events:number;bookings:number};customers:Customer[];archivedCustomers:ArchivedCustomer[];bookings:Booking[];emailSettings:Record<string,string>;legalDocuments:LegalDocument[];legalVersions:LegalVersion[];logs:LogRow[]}){
 const [area,setArea]=useState<Area>("uebersicht"),[senders,setSenders]=useState<Record<string,string>>(emailSettings),[displayName,setDisplayName]=useState("RescueEd Alert"),[saveState,setSaveState]=useState(""),[documents,setDocuments]=useState(legalDocuments),[legalState,setLegalState]=useState(""),[customerQuery,setCustomerQuery]=useState("");
 const initialMonth=bookings[0]?.createdAt.slice(0,7)||new Date().toISOString().slice(0,7),[month,setMonth]=useState(initialMonth);
 useEffect(()=>{const select=()=>{const id=location.hash.slice(1) as Area;if(areas.some(x=>x.id===id))setArea(id);else{setArea("uebersicht");if(id)history.replaceState(null,"","#uebersicht")}};select();addEventListener("hashchange",select);return()=>removeEventListener("hashchange",select)},[]);
 const open=(id:Area)=>{setArea(id);history.replaceState(null,"",`#${id}`);scrollTo({top:0,behavior:"smooth"})};
 const monthly=useMemo(()=>bookings.filter(x=>x.createdAt.slice(0,7)===month),[bookings,month]),total=monthly.reduce((sum,x)=>sum+x.amount,0);
 const normalizedCustomerQuery=customerQuery.trim().toLocaleLowerCase("de"),filteredCustomers=useMemo(()=>normalizedCustomerQuery?customers.filter(customer=>[customer.name,customer.organization,customer.email,customer.status,customer.accountType==="consumer"?"privat app abo":"organisation saas",customer.subscription?.status||"",customer.subscription?.store||"",customer.status==="active"?"aktiv":"gesperrt",customer.complimentaryAccess?"kostenlos":"kostenpflichtig",customer.unlimitedEventDuration?"dauernutzer":"zeitlimit"].join(" ").toLocaleLowerCase("de").includes(normalizedCustomerQuery)):customers,[customers,normalizedCustomerQuery]),filteredArchivedCustomers=useMemo(()=>normalizedCustomerQuery?archivedCustomers.filter(customer=>[customer.name,customer.organization,customer.email,customer.legalVersions,"archiv gelöscht"].join(" ").toLocaleLowerCase("de").includes(normalizedCustomerQuery)):archivedCustomers,[archivedCustomers,normalizedCustomerQuery]);
 async function saveEmailSettings(e:FormEvent){e.preventDefault();setSaveState("Wird gespeichert …");const r=await fetch("/api/unternehmer/email-settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({settings:senders,displayName})}),d=await r.json() as {error?:string};setSaveState(r.ok?"Einstellungen gespeichert.":d.error||"Speichern fehlgeschlagen.")}
 async function saveLegal(document:LegalDocument){setLegalState(`${document.documentKey}:saving`);const r=await fetch("/api/unternehmer/legal-documents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(document)}),d=await r.json() as {error?:string};if(r.ok){location.reload();return}setLegalState(`${document.documentKey}:${d.error||"Speichern fehlgeschlagen."}`)}
 return <main className="owner owner-tabs"><aside><div className="ownerbrand"><RescueEdLogo className="brand-logo--owner"/><div><b>RescueEd Alert</b><span>Unternehmerbereich</span></div></div><nav aria-label="Unternehmerbereiche">{areas.map(item=><button key={item.id} className={area===item.id?"selected":""} onClick={()=>open(item.id)} aria-current={area===item.id?"page":undefined}>{item.icon}<span>{item.label}</span></button>)}</nav><div className="asidebottom"><Link className="backtosite" href="/">← Zur SaaS</Link><LogoutButton/></div></aside><section className="ownercontent"><header><div><p>INTERNER SAAS-BEREICH</p><h1>{areas.find(x=>x.id===area)?.label}</h1><span>{subtitle(area)}</span></div><div className="operator"><ShieldCheck/><span><b>{operator.name}</b>{operator.email}</span></div></header>
 {area==="uebersicht"&&<AreaPanel><div className="stats"><Stat icon={<Building2/>} label="Organisationen" value={counts.organizations}/><Stat icon={<Users/>} label="Kundenkonten" value={counts.customers}/><Stat icon={<CalendarDays/>} label="Erstellte Events" value={counts.events}/><Stat icon={<FileSpreadsheet/>} label="Buchungen" value={counts.bookings}/></div><div className="overviewgrid"><Summary title="Kundenverwaltung" value={`${counts.customers} registrierte Kunden`} action="Kunden öffnen" onClick={()=>open("kunden")}/><Summary title="Monatsabrechnung" value={`${counts.bookings} Buchungen insgesamt`} action="Buchungen öffnen" onClick={()=>open("rechnungen")}/><Summary title="E-Mail-Absender" value="4 Aktionen konfigurierbar" action="Einstellungen öffnen" onClick={()=>open("emails")}/></div></AreaPanel>}
 {area==="kunden"&&<AreaPanel title="Kundenverwaltung" icon={<Users/>}>
  <div className="customer-search"><Search/><label><span>Kunden suchen und filtern</span><input type="search" value={customerQuery} onChange={event=>setCustomerQuery(event.target.value)} placeholder="Name, E-Mail, Kontoart oder Abo-Status"/></label>{customerQuery&&<button type="button" aria-label="Suche zurücksetzen" title="Suche zurücksetzen" onClick={()=>setCustomerQuery("")}><X/></button>}<small>{filteredCustomers.length} aktive · {filteredArchivedCustomers.length} archivierte Treffer</small></div>
  {filteredCustomers.length?<div className="tablewrap"><table><thead><tr><th>Kunde / Organisation</th><th>Kontakt</th><th>Status</th><th>Kontoart / App-Abo</th><th>Kostenfreigabe</th><th>Eventdauer</th><th>Registriert</th><th>Aktionen</th></tr></thead><tbody>{filteredCustomers.map(c=><tr key={c.id}><td><b>{c.name}</b><small>{c.organization}</small></td><td>{c.email}</td><td><span className={`status ${c.status}`}>{c.status==="active"?"Aktiv":"Gesperrt"}</span></td><td>{c.accountType==="consumer"?<><b>Privat · App</b><small>{c.subscription?`${c.subscription.store} · ${c.subscription.status}${c.subscription.expiresAt?` · bis ${date(c.subscription.expiresAt)}`:""}`:"Noch kein Abo zugeordnet"}</small><small>{c.subscription?.lastVerifiedAt?`Zuletzt geprüft: ${dateTime(c.subscription.lastVerifiedAt)}`:"Live-Prüfung nur bei App-Nutzung"}</small></>:"Organisation · SaaS"}</td><td>{c.accountType==="consumer"?"Nur Store-Abo":<ComplimentaryAccessToggle userId={c.id} enabled={c.complimentaryAccess}/>}</td><td>{c.accountType==="consumer"?"Max. 48 h":<UnlimitedEventDurationToggle userId={c.id} enabled={c.unlimitedEventDuration}/>}</td><td>{date(c.createdAt)}</td><td><div className="rowactions"><PasswordLinkButton userId={c.id}/><UserStatusButton userId={c.id} status={c.status}/></div></td></tr>)}</tbody></table></div>:<Empty text={normalizedCustomerQuery?"Keine aktiven Kunden für diesen Filter gefunden.":"Noch keine aktiven Kundenregistrierungen vorhanden."}/>}
  <section className="customer-archive"><header><div><h3>Löscharchiv</h3><p>Vom Kunden gelöschte Zugänge mit Vertrags- und Einwilligungsnachweisen.</p></div><span>{filteredArchivedCustomers.length}</span></header>{filteredArchivedCustomers.length?<div className="tablewrap"><table><thead><tr><th>Kunde / Organisation</th><th>Archivierter Kontakt</th><th>Rechtsnachweise</th><th>Gelöscht</th><th>Aufbewahrung prüfen</th></tr></thead><tbody>{filteredArchivedCustomers.map(c=><tr key={c.id}><td><b>{c.name}</b><small>{c.organization}</small></td><td>{c.email}</td><td><small>{c.legalVersions}</small></td><td>{dateTime(c.deletedAt)}</td><td>{date(c.retentionReviewAt)}</td></tr>)}</tbody></table></div>:<Empty text={normalizedCustomerQuery?"Keine archivierten Kunden für diesen Filter gefunden.":"Das Löscharchiv ist leer."}/>}<p className="archive-note">Der Prüftermin löst keine automatische Löschung aus. Die weitere Aufbewahrung ist anhand der geltenden gesetzlichen und vertraglichen Pflichten zu prüfen.</p></section>
 </AreaPanel>}
 {area==="kunden"&&filteredArchivedCustomers.some(customer=>customer.legalEvidence.length>0)&&<AreaPanel title="Archivierte Rechtsnachweise" icon={<ScrollText/>}><div className="legaldocuments">{filteredArchivedCustomers.filter(customer=>customer.legalEvidence.length>0).map(customer=><details key={customer.id} className="legal-version"><summary>{customer.organization} · {customer.name} · gelöscht {date(customer.deletedAt)}</summary>{customer.legalEvidence.map(document=><article key={`${customer.id}-${document.documentKey}-${document.version}`}><b>{document.title||document.documentKey} · {document.version}</b><p>Bestätigt: {dateTime(document.acceptedAt)} · SHA-256: <code>{document.contentHash}</code></p><div className="legal-version-content">{document.content||"Historischer Inhalt nicht verfügbar"}</div></article>)}</details>)}</div></AreaPanel>}
 {area==="rechnungen"&&<AreaPanel title="Monatliche Buchungsliste" icon={<FileSpreadsheet/>}><div className="billingtools"><label>Abrechnungsmonat<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div><span>Monatssumme</span><b>{money(total)}</b></div><a className="exportbutton" href={`/api/unternehmer/billing-export?month=${month}`} download><Download/> CSV für Excel / DATEV exportieren</a></div>{monthly.length?<div className="tablewrap"><table><thead><tr><th>Buchungsdatum</th><th>Kunde / Organisation</th><th>Gebuchte Leistung</th><th>Rechnungs-E-Mail</th><th>Betrag</th></tr></thead><tbody>{monthly.map(b=><tr key={b.id}><td>{date(b.createdAt)}</td><td><b>{b.customer}</b><small>{b.organization}</small></td><td>Event-Paket bis {b.helperLimit} Helfer</td><td>{b.email}</td><td><b>{money(b.amount)}</b></td></tr>)}</tbody></table></div>:<Empty text="Für diesen Monat liegen keine Buchungen vor. Der Export enthält nur die Spaltenüberschriften."/>}<p className="exportnote">CSV mit Semikolon-Trennung, UTF-8 und deutschem Dezimalformat. Direkt mit Excel sowie vielen DATEV- und Abrechnungsimporten verwendbar.</p></AreaPanel>}
 {area==="emails"&&<AreaPanel title="Absenderadressen nach Aktion" icon={<Mail/>}><div className="settingshint"><Mail/><span><b>Kein E-Mail-Postfach</b>Hier wird ausschließlich festgelegt, welche Absenderadresse die SaaS für die jeweilige automatische Aktion verwendet.</span></div><form className="emailsettings" onSubmit={saveEmailSettings}><label className="displayname">Angezeigter Absendername<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required/></label>{emailActions.map(item=><label key={item.id}><span><b>{item.title}</b><small>{item.copy}</small></span><input type="email" value={senders[item.id]||""} onChange={e=>setSenders(x=>({...x,[item.id]:e.target.value}))} placeholder="noreply@rescueed.de" required/></label>)}<div className="settingsfooter"><button>E-Mail-Einstellungen speichern</button>{saveState&&<span role="status">{saveState}</span>}</div></form></AreaPanel>}
 {area==="rechtliches"&&<AreaPanel title="Rechtliche Dokumente" icon={<BookOpen/>}><div className="legaldocuments">{documents.map((document,index)=><article key={document.documentKey}><div className="legaldochead"><div><b>{document.title}</b><a href={`/rechtliches/${document.documentKey}`} target="_blank">Öffentliche Ansicht</a></div><label>Status<select value={document.status} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,status:e.target.value as "draft"|"published"}:item))}><option value="draft">Entwurf</option><option value="published">Veröffentlicht</option></select></label></div><label>Titel<input value={document.title} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,title:e.target.value}:item))}/></label><label>Version<input value={document.version} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,version:e.target.value}:item))}/></label><label>Inhalt<textarea rows={9} value={document.content} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,content:e.target.value}:item))}/></label><footer><button onClick={()=>saveLegal(document)}>Dokument speichern</button>{legalState===`${document.documentKey}:saving`&&<span>Wird gespeichert …</span>}{legalState===`${document.documentKey}:saved`&&<span>Gespeichert.</span>}{legalState.startsWith(`${document.documentKey}:`)&&!legalState.endsWith(":saving")&&!legalState.endsWith(":saved")&&<span className="error">{legalState.split(":").slice(1).join(":")}</span>}</footer></article>)}</div></AreaPanel>}
 {area==="rechtliches"&&<AreaPanel title="Veröffentlichte Fassungen und Archiv" icon={<ScrollText/>}><p>Veröffentlichte Inhalte bleiben unveränderlich. Für Änderungen eine neue Versionsnummer vergeben; die vorherige Fassung wird archiviert.</p><div className="legaldocuments">{legalVersions.length?legalVersions.map(version=><details key={`${version.documentKey}-${version.version}`} className="legal-version"><summary>{version.title} · {version.version} · {version.archivedAt?`Archiviert ${date(version.archivedAt)}`:"Aktuelle Fassung"}</summary><p>Veröffentlicht: {dateTime(version.publishedAt)} · SHA-256: <code>{version.contentHash}</code></p><div className="legal-version-content">{version.content}</div></details>):<Empty text="Noch keine Fassung veröffentlicht."/>}</div></AreaPanel>}
 {area==="sicherheit"&&<AreaPanel title="Sicherheit & Audit" icon={<ScrollText/>}><div className="securitycards"><p><ShieldCheck/><span><b>Rollenbasierter Zugriff</b>Nur Plattforminhaber dürfen diesen Bereich öffnen.</span></p><p><ShieldCheck/><span><b>Sicherheitscodes und Sitzungen</b>Sicherheitscode, Ablaufzeit und geschützte Cookies.</span></p><p><ShieldCheck/><span><b>Passwortlinks</b>Einmalig, gehasht und 30 Minuten gültig.</span></p></div>{logs.length?<div className="auditrows">{logs.map(l=><article key={l.id}><b>{auditLabel(l.action)}</b><span>{entityLabel(l.entityType)}</span><time>{dateTime(l.createdAt)}</time></article>)}</div>:<Empty text="Noch keine Audit-Einträge vorhanden."/>}</AreaPanel>}
 </section></main>}
function AreaPanel({title,icon,children}:{title?:string;icon?:ReactNode;children:ReactNode}){return <section className="area-panel" role="tabpanel">{title&&<h2>{icon}{title}</h2>}{children}</section>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <article className="stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></article>}
function Summary({title,value,action,onClick}:{title:string;value:string;action:string;onClick:()=>void}){return <article className="summary"><b>{title}</b><span>{value}</span><button onClick={onClick}>{action} →</button></article>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function subtitle(area:Area){return ({uebersicht:"Alle wichtigen Plattformdaten auf einen Blick.",kunden:"Registrierungen, Zugänge und Kundenstatus verwalten.",rechnungen:"Monatsweise Buchungen prüfen und für die Abrechnung exportieren.",emails:"Absenderadressen für automatische Aktionen festlegen.",rechtliches:"AGB, Datenschutz, Impressum, AVV und SLA versioniert verwalten.",sicherheit:"Zugriffe und sicherheitsrelevante Änderungen nachvollziehen."} as Record<Area,string>)[area]}
function date(value:string){return new Intl.DateTimeFormat("de-DE").format(new Date(value))}
function dateTime(value:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function money(cents:number){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(cents/100)}
function auditLabel(value:string){return ({"password_link.created":"Passwortlink erstellt","password.changed":"Passwort geändert","registration.completed":"Registrierung abgeschlossen","user.active":"Konto entsperrt","user.blocked":"Konto gesperrt","customer.complimentary_enabled":"Kostenlose Nutzung aktiviert","customer.complimentary_disabled":"Kostenlose Nutzung deaktiviert","customer.unlimited_duration_enabled":"Dauernutzer aktiviert","customer.unlimited_duration_disabled":"Dauernutzer deaktiviert","account.deleted_by_customer":"Account durch Kunden gelöscht","email_settings.updated":"E-Mail-Einstellungen geändert","legal_document.updated":"Rechtstext geändert"} as Record<string,string>)[value]||value}
function entityLabel(value:string){return ({user:"Benutzerkonto",organization:"Organisation",invoice:"Buchung",event:"Event",email_settings:"E-Mail-Einstellungen",legal_document:"Rechtstext",deleted_customer_archive:"Löscharchiv"} as Record<string,string>)[value]||value}
