"use client";
import {FormEvent,useEffect,useMemo,useState,type ReactNode} from "react";
import {BookOpen,Building2,CalendarDays,Download,FileSpreadsheet,LayoutDashboard,Mail,ScrollText,ShieldCheck,Users} from "lucide-react";
import {RescueEdLogo} from "@/components/brand-logo";
import {LogoutButton,PasswordLinkButton,UserStatusButton} from "./actions";
type Area="uebersicht"|"kunden"|"events"|"rechnungen"|"emails"|"rechtliches"|"sicherheit";
type Customer={id:string;name:string;email:string;status:string;organization:string;createdAt:string};
type EventRow={id:string;customer:string;organization:string;createdAt:string};
type Booking={id:string;customer:string;organization:string;email:string;helperLimit:number;amount:number;currency:string;createdAt:string};
type LogRow={id:string;action:string;entityType:string;createdAt:string};
type EmailAction="mfa"|"registration_link"|"password_reset"|"customer_contact";
type LegalKey="agb"|"datenschutz"|"impressum"|"avv"|"sla";
type LegalDocument={documentKey:LegalKey;title:string;version:string;content:string;status:"draft"|"published"};
const areas:{id:Area;label:string;icon:ReactNode}[]=[{id:"uebersicht",label:"Übersicht",icon:<LayoutDashboard/>},{id:"kunden",label:"Kundenverwaltung",icon:<Users/>},{id:"events",label:"Erstellte Events",icon:<CalendarDays/>},{id:"rechnungen",label:"Buchungen & Export",icon:<FileSpreadsheet/>},{id:"emails",label:"E-Mail-Einstellungen",icon:<Mail/>},{id:"rechtliches",label:"Rechtliches",icon:<BookOpen/>},{id:"sicherheit",label:"Sicherheit & Audit",icon:<ShieldCheck/>}];
const emailActions:{id:EmailAction;title:string;copy:string}[]=[{id:"mfa",title:"Sicherheitscode",copy:"Absender für Sicherheitscodes bei der Anmeldung."},{id:"registration_link",title:"Registrierungslink",copy:"Absender für die Einrichtung neuer Kundenkonten."},{id:"password_reset",title:"Passwort vergessen",copy:"Absender für Links zum Zurücksetzen des Passworts."},{id:"customer_contact",title:"Allgemeiner Kundenkontakt",copy:"Absender für Vertrags- und Serviceinformationen."}];
export function OwnerDashboard({operator,counts,customers,events,bookings,emailSettings,legalDocuments,logs}:{operator:{name:string;email:string};counts:{organizations:number;customers:number;events:number;bookings:number};customers:Customer[];events:EventRow[];bookings:Booking[];emailSettings:Record<string,string>;legalDocuments:LegalDocument[];logs:LogRow[]}){
 const [area,setArea]=useState<Area>("uebersicht"),[senders,setSenders]=useState<Record<string,string>>(emailSettings),[displayName,setDisplayName]=useState("RescueEd Alert"),[saveState,setSaveState]=useState(""),[documents,setDocuments]=useState(legalDocuments),[legalState,setLegalState]=useState("");
 const initialMonth=bookings[0]?.createdAt.slice(0,7)||new Date().toISOString().slice(0,7),[month,setMonth]=useState(initialMonth);
 useEffect(()=>{const select=()=>{const id=location.hash.slice(1) as Area;if(areas.some(x=>x.id===id))setArea(id)};select();addEventListener("hashchange",select);return()=>removeEventListener("hashchange",select)},[]);
 const open=(id:Area)=>{setArea(id);history.replaceState(null,"",`#${id}`);scrollTo({top:0,behavior:"smooth"})};
 const monthly=useMemo(()=>bookings.filter(x=>x.createdAt.slice(0,7)===month),[bookings,month]),total=monthly.reduce((sum,x)=>sum+x.amount,0);
 async function saveEmailSettings(e:FormEvent){e.preventDefault();setSaveState("Wird gespeichert …");const r=await fetch("/api/unternehmer/email-settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({settings:senders,displayName})}),d=await r.json() as {error?:string};setSaveState(r.ok?"Einstellungen gespeichert.":d.error||"Speichern fehlgeschlagen.")}
 async function saveLegal(document:LegalDocument){setLegalState(`${document.documentKey}:saving`);const r=await fetch("/api/unternehmer/legal-documents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(document)}),d=await r.json() as {error?:string};setLegalState(r.ok?`${document.documentKey}:saved`:`${document.documentKey}:${d.error||"Speichern fehlgeschlagen."}`)}
 return <main className="owner owner-tabs"><aside><div className="ownerbrand"><RescueEdLogo className="brand-logo--owner"/><div><b>RescueEd Alert</b><span>Unternehmerbereich</span></div></div><nav aria-label="Unternehmerbereiche">{areas.map(item=><button key={item.id} className={area===item.id?"selected":""} onClick={()=>open(item.id)} aria-current={area===item.id?"page":undefined}>{item.icon}<span>{item.label}</span></button>)}</nav><div className="asidebottom"><a className="backtosite" href="/">← Zur SaaS</a><LogoutButton/></div></aside><section className="ownercontent"><header><div><p>INTERNER SAAS-BEREICH</p><h1>{areas.find(x=>x.id===area)?.label}</h1><span>{subtitle(area)}</span></div><div className="operator"><ShieldCheck/><span><b>{operator.name}</b>{operator.email}</span></div></header>
 {area==="uebersicht"&&<AreaPanel><div className="stats"><Stat icon={<Building2/>} label="Organisationen" value={counts.organizations}/><Stat icon={<Users/>} label="Kundenkonten" value={counts.customers}/><Stat icon={<CalendarDays/>} label="Erstellte Events" value={counts.events}/><Stat icon={<FileSpreadsheet/>} label="Buchungen" value={counts.bookings}/></div><div className="overviewgrid"><Summary title="Kundenverwaltung" value={`${counts.customers} registrierte Kunden`} action="Kunden öffnen" onClick={()=>open("kunden")}/><Summary title="Monatsabrechnung" value={`${counts.bookings} Buchungen insgesamt`} action="Buchungen öffnen" onClick={()=>open("rechnungen")}/><Summary title="E-Mail-Absender" value="4 Aktionen konfigurierbar" action="Einstellungen öffnen" onClick={()=>open("emails")}/></div></AreaPanel>}
 {area==="kunden"&&<AreaPanel title="Kundenverwaltung" icon={<Users/>}>{customers.length?<div className="tablewrap"><table><thead><tr><th>Kunde / Organisation</th><th>Kontakt</th><th>Status</th><th>Registriert</th><th>Aktionen</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><b>{c.name}</b><small>{c.organization}</small></td><td>{c.email}</td><td><span className={`status ${c.status}`}>{c.status==="active"?"Aktiv":"Gesperrt"}</span></td><td>{date(c.createdAt)}</td><td><div className="rowactions"><PasswordLinkButton userId={c.id}/><UserStatusButton userId={c.id} status={c.status}/></div></td></tr>)}</tbody></table></div>:<Empty text="Noch keine Kundenregistrierungen vorhanden."/>}</AreaPanel>}
 {area==="events"&&<AreaPanel title="Datenschutzarmes Eventprotokoll" icon={<CalendarDays/>}><div className="privacyhint"><ShieldCheck/><span><b>Datenschutz berücksichtigt</b>Eventnamen, Einsatzorte, Helferzahlen und Einsatzdetails werden hier nicht angezeigt.</span></div>{events.length?<div className="eventlog">{events.map(e=><article key={e.id}><CalendarDays/><div><b>Von Kunde {e.customer} erstelltes Event</b><span>{e.organization}</span></div><time>am {dateTime(e.createdAt)}</time></article>)}</div>:<Empty text="Noch keine Events von Kunden erstellt."/>}</AreaPanel>}
 {area==="rechnungen"&&<AreaPanel title="Monatliche Buchungsliste" icon={<FileSpreadsheet/>}><div className="billingtools"><label>Abrechnungsmonat<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div><span>Monatssumme</span><b>{money(total)}</b></div><a className="exportbutton" href={`/api/unternehmer/billing-export?month=${month}`} download><Download/> CSV für Excel / DATEV exportieren</a></div>{monthly.length?<div className="tablewrap"><table><thead><tr><th>Buchungsdatum</th><th>Kunde / Organisation</th><th>Gebuchte Leistung</th><th>Rechnungs-E-Mail</th><th>Betrag</th></tr></thead><tbody>{monthly.map(b=><tr key={b.id}><td>{date(b.createdAt)}</td><td><b>{b.customer}</b><small>{b.organization}</small></td><td>Event-Paket bis {b.helperLimit} Helfer</td><td>{b.email}</td><td><b>{money(b.amount)}</b></td></tr>)}</tbody></table></div>:<Empty text="Für diesen Monat liegen keine Buchungen vor. Der Export enthält nur die Spaltenüberschriften."/>}<p className="exportnote">CSV mit Semikolon-Trennung, UTF-8 und deutschem Dezimalformat. Direkt mit Excel sowie vielen DATEV- und Abrechnungsimporten verwendbar.</p></AreaPanel>}
 {area==="emails"&&<AreaPanel title="Absenderadressen nach Aktion" icon={<Mail/>}><div className="settingshint"><Mail/><span><b>Kein E-Mail-Postfach</b>Hier wird ausschließlich festgelegt, welche Absenderadresse die SaaS für die jeweilige automatische Aktion verwendet.</span></div><form className="emailsettings" onSubmit={saveEmailSettings}><label className="displayname">Angezeigter Absendername<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required/></label>{emailActions.map(item=><label key={item.id}><span><b>{item.title}</b><small>{item.copy}</small></span><input type="email" value={senders[item.id]||""} onChange={e=>setSenders(x=>({...x,[item.id]:e.target.value}))} placeholder="noreply@rescueed.de" required/></label>)}<div className="settingsfooter"><button>E-Mail-Einstellungen speichern</button>{saveState&&<span role="status">{saveState}</span>}</div></form></AreaPanel>}
 {area==="rechtliches"&&<AreaPanel title="Rechtliche Dokumente" icon={<BookOpen/>}><div className="legalnotice"><ShieldCheck/><span><b>Vor Produktivbetrieb prüfen lassen</b>Die hinterlegten Texte sind bearbeitbare Entwürfe und keine Rechtsberatung. Nur als „veröffentlicht“ markierte Fassungen sollten Kunden verbindlich angezeigt werden.</span></div><div className="legaldocuments">{documents.map((document,index)=><article key={document.documentKey}><div className="legaldochead"><div><b>{document.title}</b><a href={`/rechtliches/${document.documentKey}`} target="_blank">Öffentliche Ansicht</a></div><label>Status<select value={document.status} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,status:e.target.value as "draft"|"published"}:item))}><option value="draft">Entwurf</option><option value="published">Veröffentlicht</option></select></label></div><label>Titel<input value={document.title} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,title:e.target.value}:item))}/></label><label>Version<input value={document.version} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,version:e.target.value}:item))}/></label><label>Inhalt<textarea rows={9} value={document.content} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,content:e.target.value}:item))}/></label><footer><button onClick={()=>saveLegal(document)}>Dokument speichern</button>{legalState===`${document.documentKey}:saving`&&<span>Wird gespeichert …</span>}{legalState===`${document.documentKey}:saved`&&<span>Gespeichert.</span>}{legalState.startsWith(`${document.documentKey}:`)&&!legalState.endsWith(":saving")&&!legalState.endsWith(":saved")&&<span className="error">{legalState.split(":").slice(1).join(":")}</span>}</footer></article>)}</div></AreaPanel>}
 {area==="sicherheit"&&<AreaPanel title="Sicherheit & Audit" icon={<ScrollText/>}><div className="securitycards"><p><ShieldCheck/><span><b>Rollenbasierter Zugriff</b>Nur Plattforminhaber dürfen diesen Bereich öffnen.</span></p><p><ShieldCheck/><span><b>Sicherheitscodes und Sitzungen</b>Sicherheitscode, Ablaufzeit und geschützte Cookies.</span></p><p><ShieldCheck/><span><b>Passwortlinks</b>Einmalig, gehasht und 30 Minuten gültig.</span></p></div>{logs.length?<div className="auditrows">{logs.map(l=><article key={l.id}><b>{auditLabel(l.action)}</b><span>{entityLabel(l.entityType)}</span><time>{dateTime(l.createdAt)}</time></article>)}</div>:<Empty text="Noch keine Audit-Einträge vorhanden."/>}</AreaPanel>}
 </section></main>}
function AreaPanel({title,icon,children}:{title?:string;icon?:ReactNode;children:ReactNode}){return <section className="area-panel" role="tabpanel">{title&&<h2>{icon}{title}</h2>}{children}</section>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <article className="stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></article>}
function Summary({title,value,action,onClick}:{title:string;value:string;action:string;onClick:()=>void}){return <article className="summary"><b>{title}</b><span>{value}</span><button onClick={onClick}>{action} →</button></article>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function subtitle(area:Area){return ({uebersicht:"Alle wichtigen Plattformdaten auf einen Blick.",kunden:"Registrierungen, Zugänge und Kundenstatus verwalten.",events:"Nur Ersteller und Erstellzeitpunkt – ohne Einsatzdetails.",rechnungen:"Monatsweise Buchungen prüfen und für die Abrechnung exportieren.",emails:"Absenderadressen für automatische Aktionen festlegen.",rechtliches:"AGB, Datenschutz, Impressum, AVV und SLA versioniert verwalten.",sicherheit:"Zugriffe und sicherheitsrelevante Änderungen nachvollziehen."} as Record<Area,string>)[area]}
function date(value:string){return new Intl.DateTimeFormat("de-DE").format(new Date(value))}
function dateTime(value:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function money(cents:number){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(cents/100)}
function auditLabel(value:string){return ({"password_link.created":"Passwortlink erstellt","password.changed":"Passwort geändert","registration.completed":"Registrierung abgeschlossen","user.active":"Konto entsperrt","user.blocked":"Konto gesperrt","email_settings.updated":"E-Mail-Einstellungen geändert","legal_document.updated":"Rechtstext geändert"} as Record<string,string>)[value]||value}
function entityLabel(value:string){return ({user:"Benutzerkonto",invoice:"Buchung",event:"Event",email_settings:"E-Mail-Einstellungen",legal_document:"Rechtstext"} as Record<string,string>)[value]||value}
