"use client";
import {FormEvent,useEffect,useMemo,useState,type ReactNode} from "react";
import Link from "next/link";
import {Archive,BookOpen,Building2,CalendarDays,Download,FileSpreadsheet,LayoutDashboard,LifeBuoy,Mail,Search,ScrollText,ShieldCheck,Users,X} from "lucide-react";
import {RescueEdLogo} from "@/components/brand-logo";
import {activeServiceLabel,organizationTypeLabel,type OrganizationType} from "@/lib/organization-type";
import {SupportPanel} from "./support-panel";
import {StaffManagement} from "./staff-management";
import {ComplimentaryAccessToggle,LogoutButton,OrganizationTypeSelect,PasswordLinkButton,UnlimitedEventDurationToggle,UserStatusButton,WithdrawalStatus} from "./actions";
type Area="uebersicht"|"kunden"|"rechnungen"|"emails"|"rechtliches"|"sicherheit"|"support"|"benutzer";
type Customer={id:string;name:string;email:string;status:string;accountType:"organization"|"consumer";organization:string;organizationType:OrganizationType|null;complimentaryAccess:boolean;unlimitedEventDuration:boolean;createdAt:string;subscription:{store:"google"|"apple";status:string;purchasedAt:string|null;expiresAt:string|null;lastVerifiedAt:string|null;withdrawal:{id:string;status:string;requestedAt:string}|null}|null};
type ArchivedCustomer={id:string;name:string;email:string;organization:string;deletedAt:string;retentionReviewAt:string;retentionHeld:boolean;legalVersions:string;legalEvidence:Array<{documentKey:string;version:string;contentHash:string;acceptedAt:string;title:string|null;content:string|null}>};
type Booking={id:string;customer:string;organization:string;email:string;helperLimit:number;amount:number;currency:string;createdAt:string};
type LogRow={id:string;action:string;entityType:string;createdAt:string};
type StaffAccount={id:string;name:string;email:string;status:string;createdAt:string;emailVerifiedAt:string|null};
type EmailAction="mfa"|"registration_link"|"password_reset"|"customer_contact";
type LegalKey="agb"|"agb_b2c"|"datenschutz"|"impressum"|"avv"|"sla"|"widerruf";
type LegalDocument={documentKey:LegalKey;title:string;version:string;content:string;status:"draft"|"published"};
type LegalVersion={documentKey:LegalKey;title:string;version:string;content:string;contentHash:string;publishedAt:string;archivedAt:string|null};
const areas:{id:Area;label:string;icon:ReactNode}[]=[{id:"uebersicht",label:"Übersicht",icon:<LayoutDashboard/>},{id:"kunden",label:"Kundenverwaltung",icon:<Users/>},{id:"rechnungen",label:"Buchungen & Export",icon:<FileSpreadsheet/>},{id:"emails",label:"E-Mail-Einstellungen",icon:<Mail/>},{id:"rechtliches",label:"Rechtliches",icon:<BookOpen/>},{id:"sicherheit",label:"Sicherheit & Audit",icon:<ShieldCheck/>},{id:"benutzer",label:"Mitarbeiter",icon:<Users/>},{id:"support",label:"Support & Fehler",icon:<LifeBuoy/>}];
const emailActions:{id:EmailAction;title:string;copy:string}[]=[{id:"mfa",title:"Sicherheitscode",copy:"Absender für Sicherheitscodes bei der Anmeldung."},{id:"registration_link",title:"Registrierungslink",copy:"Absender für die Einrichtung neuer Kundenkonten."},{id:"password_reset",title:"Passwort vergessen",copy:"Absender für Links zum Zurücksetzen des Passworts."},{id:"customer_contact",title:"Allgemeiner Kundenkontakt",copy:"Absender für Vertrags- und Serviceinformationen."}];
export function OwnerDashboard({operator,staffAccounts,counts,customers,archivedCustomers,bookings,emailSettings,legalDocuments,legalVersions,logs}:{operator:{name:string;email:string;role:"platform_owner"};staffAccounts:StaffAccount[];counts:{organizations:number;customers:number;events:number;bookings:number};customers:Customer[];archivedCustomers:ArchivedCustomer[];bookings:Booking[];emailSettings:Record<string,string>;legalDocuments:LegalDocument[];legalVersions:LegalVersion[];logs:LogRow[]}){
 const [area,setArea]=useState<Area>("uebersicht"),[senders,setSenders]=useState<Record<string,string>>(emailSettings),[displayName,setDisplayName]=useState("RescueEd Alert"),[saveState,setSaveState]=useState(""),[documents,setDocuments]=useState(legalDocuments),[legalState,setLegalState]=useState(""),[customerQuery,setCustomerQuery]=useState("");
 const initialMonth=bookings[0]?.createdAt.slice(0,7)||new Date().toISOString().slice(0,7),[month,setMonth]=useState(initialMonth);
 useEffect(()=>{const select=()=>{const id=location.hash.slice(1) as Area;if(areas.some(x=>x.id===id))setArea(id);else{setArea("uebersicht");if(id)history.replaceState(null,"","#uebersicht")}};select();addEventListener("hashchange",select);return()=>removeEventListener("hashchange",select)},[]);
 const open=(id:Area)=>{setArea(id);history.replaceState(null,"",`#${id}`);scrollTo({top:0,behavior:"smooth"})};
 const monthly=useMemo(()=>bookings.filter(x=>x.createdAt.slice(0,7)===month),[bookings,month]),total=monthly.reduce((sum,x)=>sum+x.amount,0);
 const normalizedCustomerQuery=customerQuery.trim().toLocaleLowerCase("de"),filteredCustomers=useMemo(()=>normalizedCustomerQuery?customers.filter(customer=>[customer.name,customer.organization,customer.email,customer.status,organizationTypeLabel(customer.organizationType),customer.accountType==="consumer"?"privat app abo":"organisation saas",customer.subscription?.status||"",customer.subscription?.store||"",customer.status==="active"?"aktiv":"gesperrt",customer.complimentaryAccess?"kostenlos":"kostenpflichtig",customer.unlimitedEventDuration?"dauernutzer":"zeitlimit"].join(" ").toLocaleLowerCase("de").includes(normalizedCustomerQuery)):customers,[customers,normalizedCustomerQuery]),filteredArchivedCustomers=useMemo(()=>normalizedCustomerQuery?archivedCustomers.filter(customer=>[customer.name,customer.organization,customer.email,customer.legalVersions,"archiv gelöscht"].join(" ").toLocaleLowerCase("de").includes(normalizedCustomerQuery)):archivedCustomers,[archivedCustomers,normalizedCustomerQuery]);
 async function saveEmailSettings(e:FormEvent){e.preventDefault();setSaveState("Wird gespeichert …");const r=await fetch("/api/unternehmer/email-settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({settings:senders,displayName})}),d=await r.json() as {error?:string};setSaveState(r.ok?"Einstellungen gespeichert.":d.error||"Speichern fehlgeschlagen.")}
 async function saveLegal(document:LegalDocument){setLegalState(`${document.documentKey}:saving`);const r=await fetch("/api/unternehmer/legal-documents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(document)}),d=await r.json() as {error?:string};if(r.ok){location.reload();return}setLegalState(`${document.documentKey}:${d.error||"Speichern fehlgeschlagen."}`)}
 return <main className="owner owner-tabs"><aside><div className="ownerbrand"><RescueEdLogo className="brand-logo--owner"/><div><b>RescueEd Alert</b><span>Unternehmerbereich</span></div></div><nav aria-label="Unternehmerbereiche">{areas.map(item=><button key={item.id} className={area===item.id?"selected":""} onClick={()=>open(item.id)} aria-current={area===item.id?"page":undefined}>{item.icon}<span>{item.label}</span></button>)}<Link className="archive-nav-link" href="/unternehmer/archiv"><Archive/><span>Archiv & Nachweise</span></Link></nav><div className="asidebottom"><Link className="backtosite" href="/profil">Mein Profil</Link><Link className="backtosite" href="/">← Zur SaaS</Link><LogoutButton/></div></aside><section className="ownercontent"><header><div><p>INTERNER SAAS-BEREICH</p><h1>{areas.find(x=>x.id===area)?.label}</h1><span>{subtitle(area)}</span></div><div className="operator"><Link href="/profil">Mein Profil</Link><ShieldCheck/><span><b>{operator.name}</b>{operator.email}</span></div></header>
 {area==="uebersicht"&&<AreaPanel><div className="stats"><Stat icon={<Building2/>} label="Organisationen" value={counts.organizations}/><Stat icon={<Users/>} label="Kundenkonten" value={counts.customers}/><Stat icon={<CalendarDays/>} label="Erstellte Events" value={counts.events}/><Stat icon={<FileSpreadsheet/>} label="Buchungen" value={counts.bookings}/></div><div className="overviewgrid"><Summary title="Kundenverwaltung" value={`${counts.customers} registrierte Kunden`} action="Kunden öffnen" onClick={()=>open("kunden")}/><Summary title="Monatsabrechnung" value={`${counts.bookings} Buchungen insgesamt`} action="Buchungen öffnen" onClick={()=>open("rechnungen")}/><Summary title="E-Mail-Absender" value="4 Aktionen konfigurierbar" action="Einstellungen öffnen" onClick={()=>open("emails")}/></div></AreaPanel>}
 {area==="kunden"&&<AreaPanel title="Kundenverwaltung" icon={<Users/>}>
  <div className="customer-search"><Search/><label><span>Kunden suchen und filtern</span><input type="search" value={customerQuery} onChange={event=>setCustomerQuery(event.target.value)} placeholder="Name, E-Mail, Kontoart oder Abo-Status"/></label>{customerQuery&&<button type="button" aria-label="Suche zurücksetzen" title="Suche zurücksetzen" onClick={()=>setCustomerQuery("")}><X/></button>}<small>{filteredCustomers.length} aktive · {filteredArchivedCustomers.length} archivierte Treffer</small></div>
  {filteredCustomers.length
   ?<CustomerRows customers={filteredCustomers}/>
   :<Empty text={normalizedCustomerQuery?"Keine aktiven Kunden für diesen Filter gefunden.":"Noch keine aktiven Kundenregistrierungen vorhanden."}/>}
  <section className="customer-archive"><header><div><h3>Löscharchiv · Vertragsnachweise</h3><p>Minimal erforderliche Nachweise gelöschter Zugänge; Buchungsbelege werden getrennt aufbewahrt.</p></div><span>{filteredArchivedCustomers.length}</span></header>{filteredArchivedCustomers.length?<ArchivedCustomerRows customers={filteredArchivedCustomers}/>:<Empty text={normalizedCustomerQuery?"Keine archivierten Kunden für diesen Filter gefunden.":"Das Löscharchiv ist leer."}/>}<p className="archive-note">Nach Fristablauf werden Nachweise automatisch gelöscht, sofern keine dokumentierte Aufbewahrungssperre besteht. Bei App-Abos muss das Vertragsende zuvor bestätigt werden.</p></section>
 </AreaPanel>}
 {area==="rechnungen"&&<AreaPanel title="Monatliche Buchungsliste" icon={<FileSpreadsheet/>}><div className="billingtools"><label>Abrechnungsmonat<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div><span>Monatssumme</span><b>{money(total)}</b></div><a className="exportbutton" href={`/api/unternehmer/billing-export?month=${month}`} download><Download/> CSV für Excel / DATEV exportieren</a></div>{monthly.length?<div className="tablewrap"><table><thead><tr><th>Buchungsdatum</th><th>Kunde / Organisation</th><th>Gebuchte Leistung</th><th>Rechnungs-E-Mail</th><th>Betrag</th></tr></thead><tbody>{monthly.map(b=><tr key={b.id}><td>{date(b.createdAt)}</td><td><b>{b.customer}</b><small>{b.organization}</small></td><td>Event-Paket bis {b.helperLimit} Helfer</td><td>{b.email}</td><td><b>{money(b.amount)}</b></td></tr>)}</tbody></table></div>:<Empty text="Für diesen Monat liegen keine Buchungen vor. Der Export enthält nur die Spaltenüberschriften."/>}<p className="exportnote">CSV mit Semikolon-Trennung, UTF-8 und deutschem Dezimalformat. Direkt mit Excel sowie vielen DATEV- und Abrechnungsimporten verwendbar.</p></AreaPanel>}
 {area==="emails"&&<AreaPanel title="Absenderadressen nach Aktion" icon={<Mail/>}><div className="settingshint"><Mail/><span><b>Kein E-Mail-Postfach</b>Hier wird ausschließlich festgelegt, welche Absenderadresse die SaaS für die jeweilige automatische Aktion verwendet.</span></div><form className="emailsettings" onSubmit={saveEmailSettings}><label className="displayname">Angezeigter Absendername<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required/></label>{emailActions.map(item=><label key={item.id}><span><b>{item.title}</b><small>{item.copy}</small></span><input type="email" value={senders[item.id]||""} onChange={e=>setSenders(x=>({...x,[item.id]:e.target.value}))} placeholder="noreply@rescueed.de" required/></label>)}<div className="settingsfooter"><button>E-Mail-Einstellungen speichern</button>{saveState&&<span role="status">{saveState}</span>}</div></form></AreaPanel>}
 {area==="rechtliches"&&<AreaPanel title="Rechtliche Dokumente" icon={<BookOpen/>}><div className="legaldocuments">{documents.map((document,index)=><article key={document.documentKey}><div className="legaldochead"><div><b>{document.title}</b><a href={`/rechtliches/${document.documentKey}`} target="_blank">Öffentliche Ansicht</a></div><label>Status<select value={document.status} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,status:e.target.value as "draft"|"published"}:item))}><option value="draft">Entwurf</option><option value="published">Veröffentlicht</option></select></label></div><label>Titel<input value={document.title} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,title:e.target.value}:item))}/></label><label>Version<input value={document.version} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,version:e.target.value}:item))}/></label><label>Inhalt<textarea rows={9} value={document.content} onChange={e=>setDocuments(items=>items.map((item,i)=>i===index?{...item,content:e.target.value}:item))}/></label><footer><button onClick={()=>saveLegal(document)}>Dokument speichern</button>{legalState===`${document.documentKey}:saving`&&<span>Wird gespeichert …</span>}{legalState===`${document.documentKey}:saved`&&<span>Gespeichert.</span>}{legalState.startsWith(`${document.documentKey}:`)&&!legalState.endsWith(":saving")&&!legalState.endsWith(":saved")&&<span className="error">{legalState.split(":").slice(1).join(":")}</span>}</footer></article>)}</div></AreaPanel>}
 {area==="rechtliches"&&<AreaPanel title="Veröffentlichte Fassungen und Archiv" icon={<ScrollText/>}><p>Veröffentlichte Inhalte bleiben unveränderlich. Für Änderungen eine neue Versionsnummer vergeben; die vorherige Fassung wird archiviert.</p><div className="legaldocuments">{legalVersions.length?legalVersions.map(version=><details key={`${version.documentKey}-${version.version}`} className="legal-version"><summary>{version.title} · {version.version} · {version.archivedAt?`Archiviert ${date(version.archivedAt)}`:"Aktuelle Fassung"}</summary><p>Veröffentlicht: {dateTime(version.publishedAt)} · SHA-256: <code>{version.contentHash}</code></p><div className="legal-version-content">{version.content}</div></details>):<Empty text="Noch keine Fassung veröffentlicht."/>}</div></AreaPanel>}
 {area==="sicherheit"&&<AreaPanel title="Sicherheit & Audit" icon={<ScrollText/>}><div className="securitycards"><p><ShieldCheck/><span><b>Rollenbasierter Zugriff</b>Nur Plattforminhaber dürfen diesen Bereich öffnen.</span></p><p><ShieldCheck/><span><b>Sicherheitscodes und Sitzungen</b>Sicherheitscode, Ablaufzeit und geschützte Cookies.</span></p><p><ShieldCheck/><span><b>Passwortlinks</b>Einmalig, gehasht und 30 Minuten gültig.</span></p></div>{logs.length?<div className="auditrows">{logs.map(l=><article key={l.id}><b>{auditLabel(l.action)}</b><span>{entityLabel(l.entityType)}</span><time>{dateTime(l.createdAt)}</time></article>)}</div>:<Empty text="Noch keine Audit-Einträge vorhanden."/>}</AreaPanel>}
 {area==="benutzer"&&<StaffManagement accounts={staffAccounts}/>}
 {area==="support"&&<SupportPanel/>}
 </section></main>}

function CustomerRows({customers}:{customers:Customer[]}){
 return <div className="customer-rows" role="list">{customers.map(customer=><details className="customer-row" key={customer.id}>
  <summary>
   <span className="customer-identity"><b>{customer.name}</b><small>{customer.organization}</small></span>
   <span className="customer-email">{customer.email}</span>
   <span className={`customer-kind ${customer.accountType}`}>{customer.accountType==="consumer"?"Privat · App":"Organisation"}</span>
   <span className={`status ${customer.status}`}>{customer.status==="active"?"Aktiv":"Gesperrt"}</span>
   <span className="customer-more">Mehr</span>
  </summary>
  <div className="customer-row-details">
   <section><h3>Konto</h3><dl><div><dt>Registriert</dt><dd>{date(customer.createdAt)}</dd></div><div><dt>Kontoart</dt><dd>{customer.accountType==="consumer"?"Privatkonto in der App":"Organisationskonto in der SaaS"}</dd></div></dl>{customer.accountType==="organization"&&<div className="customer-control"><span><b>Organisationsart</b><small>{activeServiceLabel(customer.organizationType)}</small></span><OrganizationTypeSelect userId={customer.id} value={customer.organizationType}/></div>}</section>
   <section><h3>{customer.accountType==="consumer"?"App-Abo":"Freigaben"}</h3>{customer.accountType==="consumer"?<div className="customer-subscription">{customer.subscription?<><b>{customer.subscription.store==="google"?"Google Play":"App Store"} · {subscriptionStatusLabel(customer.subscription.status)}</b>{customer.subscription.expiresAt&&<span>Laufzeit bis {date(customer.subscription.expiresAt)}</span>}{customer.subscription.purchasedAt&&<span>Abgeschlossen {dateTime(customer.subscription.purchasedAt)}</span>}<span>{customer.subscription.lastVerifiedAt?`Zuletzt geprüft ${dateTime(customer.subscription.lastVerifiedAt)}`:"Live-Prüfung erst bei App-Nutzung"}</span>{customer.subscription.withdrawal&&<div className="customer-control"><span><b>Widerruf</b><small>Beantragt {dateTime(customer.subscription.withdrawal.requestedAt)}</small></span><WithdrawalStatus id={customer.subscription.withdrawal.id} status={customer.subscription.withdrawal.status}/></div>}</>:<span>Noch kein Store-Abo zugeordnet.</span>}<small>Eventdauer: maximal 5 Tage · Abrechnung ausschließlich über den Store</small></div>:<div className="customer-controls"><ComplimentaryAccessToggle userId={customer.id} enabled={customer.complimentaryAccess}/><UnlimitedEventDurationToggle userId={customer.id} enabled={customer.unlimitedEventDuration}/></div>}</section>
   <section><h3>Verwaltung</h3><div className="rowactions"><PasswordLinkButton userId={customer.id}/><UserStatusButton userId={customer.id} status={customer.status}/></div></section>
  </div>
 </details>)}</div>;
}

function ArchivedCustomerRows({customers}:{customers:ArchivedCustomer[]}){
 return <div className="customer-rows customer-rows--archived" role="list">{customers.map(customer=><details className="customer-row" key={customer.id}>
  <summary>
   <span className="customer-identity"><b>{customer.name}</b><small>{customer.organization}</small></span>
   <span className="customer-email">{customer.email}</span>
   <span className="customer-deleted">Gelöscht {date(customer.deletedAt)}</span>
   <span className="customer-more">Mehr</span>
  </summary>
  <div className="customer-row-details customer-row-details--archive">
   <section><h3>Aufbewahrung</h3><p>{customer.retentionHeld?`Zurückgestellt · reguläre Prüfung ab ${date(customer.retentionReviewAt)}`:`Prüfung und Löschung ab ${date(customer.retentionReviewAt)}`}</p></section>
   <section><h3>Gespeicherte Rechtsnachweise</h3><p>{customer.legalVersions||"Keine Fassungen vermerkt"}</p></section>
   {customer.legalEvidence.length>0&&<section className="customer-evidence"><h3>Historische Inhalte</h3>{customer.legalEvidence.map(document=><details key={`${customer.id}-${document.documentKey}-${document.version}`}><summary>{document.title||document.documentKey} · {document.version}</summary><p>Bestätigt: {dateTime(document.acceptedAt)} · SHA-256: <code>{document.contentHash}</code></p><div className="legal-version-content">{document.content||"Historischer Inhalt nicht verfügbar"}</div></details>)}</section>}
  </div>
 </details>)}</div>;
}

function AreaPanel({title,icon,children}:{title?:string;icon?:ReactNode;children:ReactNode}){return <section className="area-panel" role="tabpanel">{title&&<h2>{icon}{title}</h2>}{children}</section>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <article className="stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></article>}
function Summary({title,value,action,onClick}:{title:string;value:string;action:string;onClick:()=>void}){return <article className="summary"><b>{title}</b><span>{value}</span><button onClick={onClick}>{action} →</button></article>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function subtitle(area:Area){return ({uebersicht:"Alle wichtigen Plattformdaten auf einen Blick.",kunden:"Registrierungen, Zugänge und Kundenstatus verwalten.",rechnungen:"Monatsweise Buchungen prüfen und für die Abrechnung exportieren.",emails:"Absenderadressen für automatische Aktionen festlegen.",rechtliches:"AGB, Datenschutz, Impressum, AVV und SLA versioniert verwalten.",sicherheit:"Zugriffe und sicherheitsrelevante Änderungen nachvollziehen.",benutzer:"Eingeschränkte Mitarbeiterzugänge einladen und sperren.",support:"App-Fehlerberichte und Support-Tickets bearbeiten."} as Record<Area,string>)[area]}
function date(value:string){return new Intl.DateTimeFormat("de-DE").format(new Date(value))}
function dateTime(value:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function money(cents:number){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(cents/100)}
function subscriptionStatusLabel(value:string){return ({active:"Aktiv",expired:"Abgelaufen",cancelled:"Gekündigt",refunded:"Erstattet",pending:"Ausstehend"} as Record<string,string>)[value]||value}
function auditLabel(value:string){return ({"password_link.created":"Passwortlink erstellt","password.changed":"Passwort geändert","registration.completed":"Registrierung abgeschlossen","user.active":"Konto entsperrt","user.blocked":"Konto gesperrt","customer.organization_type_updated":"Organisationsart geändert","customer.complimentary_enabled":"Kostenlose Nutzung aktiviert","customer.complimentary_disabled":"Kostenlose Nutzung deaktiviert","customer.unlimited_duration_enabled":"Dauernutzer aktiviert","customer.unlimited_duration_disabled":"Dauernutzer deaktiviert","account.deleted_by_customer":"Account durch Kunden gelöscht","email_settings.updated":"E-Mail-Einstellungen geändert","legal_document.updated":"Rechtstext geändert","legal_document.published":"Rechtstext veröffentlicht","legal_documents.reconfirmed":"Rechtstexte erneut bestätigt","local_test_access_prepared":"Lokaler Testzugang vorbereitet","local_test_password_changed":"Lokales Testpasswort geändert","consumer.withdrawal_received":"Widerruf eingegangen","consumer.withdrawal_processing":"Widerruf in Bearbeitung","consumer.withdrawal_refunded":"Widerruf erstattet","consumer.withdrawal_rejected":"Widerruf ohne Erstattung abgeschlossen"} as Record<string,string>)[value]||value}
function entityLabel(value:string){return ({user:"Benutzerkonto",organization:"Organisation",invoice:"Buchung",event:"Event",email_settings:"E-Mail-Einstellungen",legal_document:"Rechtstext",deleted_customer_archive:"Löscharchiv",subscription_withdrawal:"App-Abo-Widerruf"} as Record<string,string>)[value]||value}
