"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";

type Staff={id:string;name:string;email:string;status:string;createdAt:string;emailVerifiedAt:string|null};
export function StaffManagement({accounts}:{accounts:Staff[]}){
 const router=useRouter(),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[previewUrl,setPreviewUrl]=useState("");
 async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form);setBusy("invite");setError("");const response=await fetch("/api/unternehmer/staff",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:values.get("name"),email:values.get("email")})}),result=await response.json() as {error?:string;previewUrl?:string};setBusy("");if(!response.ok){setError(result.error||"Einladung fehlgeschlagen.");return}form.reset();setPreviewUrl(result.previewUrl||"");setNotice("Mitarbeiter wurde eingeladen. Der Einrichtungslink ist 30 Minuten gültig.");router.refresh()}
 async function changeStatus(account:Staff){const status=account.status==="active"?"blocked":"active";setBusy(account.id);setError("");const response=await fetch(`/api/unternehmer/staff/${encodeURIComponent(account.id)}/status`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status})}),result=await response.json() as {error?:string};setBusy("");if(!response.ok){setError(result.error||"Statusänderung fehlgeschlagen.");return}router.refresh()}
 async function resend(account:Staff){setBusy(account.id);setError("");const response=await fetch(`/api/unternehmer/staff/${encodeURIComponent(account.id)}/resend`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),result=await response.json() as {error?:string;previewUrl?:string};setBusy("");if(!response.ok){setError(result.error||"Einladung konnte nicht erneut gesendet werden.");return}setPreviewUrl(result.previewUrl||"");setNotice("Ein neuer Einrichtungslink wurde versendet.");router.refresh()}
 return <section className="area-panel staff-panel"><h2>Unternehmer-Mitarbeiter</h2><p className="staff-intro">Zusätzliche Konten können Support bearbeiten sowie Kunden und Buchungen lesen. Rechtstexte, Sicherheit, E-Mail-Einstellungen und Benutzerverwaltung bleiben beim Betreiber.</p><form className="staff-invite" onSubmit={invite}><label>Name<input name="name" maxLength={160} required/></label><label>E-Mail-Adresse<input name="email" type="email" required/></label><button disabled={Boolean(busy)}>Per Passwortlink einladen</button></form>{error&&<p className="staff-error" role="alert">{error}</p>}{notice&&<p className="staff-notice" role="status">{notice} {previewUrl&&<a href={previewUrl}>Lokalen Link öffnen</a>}</p>}<div className="tablewrap"><table><thead><tr><th>Name</th><th>E-Mail</th><th>Status</th><th>Erstellt</th><th>Zugang</th></tr></thead><tbody>{accounts.map(account=><tr key={account.id}><td>{account.name}</td><td>{account.email}</td><td>{!account.emailVerifiedAt?"Einrichtung ausstehend":account.status==="active"?"Aktiv":"Gesperrt"}</td><td>{new Intl.DateTimeFormat("de-DE").format(new Date(account.createdAt))}</td><td>{account.emailVerifiedAt?<button className="smallaction" disabled={Boolean(busy)} onClick={()=>changeStatus(account)}>{account.status==="active"?"Sperren":"Entsperren"}</button>:<button className="smallaction" disabled={Boolean(busy)} onClick={()=>resend(account)}>Einladung erneut senden</button>}</td></tr>)}</tbody></table></div>{!accounts.length&&<p className="staff-empty">Noch keine Mitarbeiterkonten angelegt.</p>}</section>;
}
