"use client";
import {useState} from "react";
import Link from "next/link";
import {RescueEdLogo} from "@/components/brand-logo";
import {SupportPanel} from "./support-panel";
import {LogoutButton} from "./actions";

type Customer={id:string;name:string;email:string;organization:string;status:string;accountType:"organization"|"consumer"};
type Booking={id:string;customer:string;organization:string;email:string;amount:number;createdAt:string};
export function StaffDashboard({operator,customers,bookings}:{operator:{name:string;email:string};customers:Customer[];bookings:Booking[]}){
 const [tab,setTab]=useState<"support"|"kunden"|"buchungen">("support");
 return <main className="owner owner-tabs"><aside><div className="ownerbrand"><RescueEdLogo className="brand-logo--owner"/><div><b>RescueEd Alert</b><span>Unternehmer-Mitarbeiter</span></div></div><nav aria-label="Mitarbeiterbereiche"><button className={tab==="support"?"selected":""} onClick={()=>setTab("support")}>Support & Fehler</button><button className={tab==="kunden"?"selected":""} onClick={()=>setTab("kunden")}>Kunden · nur lesen</button><button className={tab==="buchungen"?"selected":""} onClick={()=>setTab("buchungen")}>Buchungen · nur lesen</button></nav><div className="asidebottom"><Link className="backtosite" href="/profil">Mein Profil</Link><LogoutButton/></div></aside><section className="ownercontent"><header><div><p>MITARBEITERBEREICH</p><h1>{tab==="support"?"Support & Fehler":tab==="kunden"?"Kundenübersicht":"Buchungsübersicht"}</h1><span>Keine Rechte zur Benutzer-, Vertrags- oder Sicherheitseinstellung.</span></div><div className="operator"><Link href="/profil">Mein Profil</Link><span><b>{operator.name}</b>{operator.email}</span></div></header>{tab==="support"?<SupportPanel/>:tab==="kunden"?<section className="area-panel"><h2>Kunden · Lesezugriff</h2><div className="tablewrap"><table><thead><tr><th>Name</th><th>Organisation</th><th>E-Mail</th><th>Status</th></tr></thead><tbody>{customers.map(customer=><tr key={customer.id}><td>{customer.name}</td><td>{customer.organization}</td><td>{customer.email}</td><td>{customer.status==="active"?"Aktiv":"Gesperrt"}</td></tr>)}</tbody></table></div></section>:<section className="area-panel"><h2>Buchungen · Lesezugriff</h2><div className="tablewrap"><table><thead><tr><th>Datum</th><th>Kunde</th><th>Organisation</th><th>Rechnungs-E-Mail</th><th>Betrag</th></tr></thead><tbody>{bookings.map(booking=><tr key={booking.id}><td>{new Intl.DateTimeFormat("de-DE").format(new Date(booking.createdAt))}</td><td>{booking.customer}</td><td>{booking.organization}</td><td>{booking.email}</td><td>{new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(booking.amount/100)}</td></tr>)}</tbody></table></div></section>}</section></main>;
}
