"use client";
import {useCallback,useEffect,useState} from "react";

type Ticket={id:string;subject:string;status:"open"|"in_progress"|"resolved";requesterType:string;requesterName:string|null;requesterEmail:string|null;eventId:string|null;createdAt:string;updatedAt:string};
type Crash={id:string;platform:string;appVersion:string;source:string;errorKind:string;stackExcerpt:string;fingerprint:string;occurredAt:string;createdAt:string};
type Message={id:string;authorType:"requester"|"support";body:string;createdAt:string};
const statusLabel={open:"Offen",in_progress:"In Bearbeitung",resolved:"Erledigt"};

export function SupportPanel(){
 const [tickets,setTickets]=useState<Ticket[]>([]),[crashes,setCrashes]=useState<Crash[]>([]),[selected,setSelected]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[reply,setReply]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const response=await fetch("/api/unternehmer/support",{cache:"no-store"}),data=await response.json() as {error?:string;tickets:Ticket[];crashes:Crash[]};if(!response.ok)throw new Error(data.error||"Supportdaten konnten nicht geladen werden.");setTickets(data.tickets);setCrashes(data.crashes);setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Supportdaten konnten nicht geladen werden.")}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function openTicket(id:string){setSelected(id);setMessages([]);try{const response=await fetch(`/api/support/tickets/${encodeURIComponent(id)}`,{cache:"no-store"}),data=await response.json() as {error?:string;messages:Message[]};if(!response.ok)throw new Error(data.error||"Ticket konnte nicht geladen werden.");setMessages(data.messages)}catch(reason){setError(reason instanceof Error?reason.message:"Ticket konnte nicht geladen werden.")}}
 async function sendReply(){if(!selected||!reply.trim())return;setBusy(true);try{const response=await fetch(`/api/support/tickets/${encodeURIComponent(selected)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:reply})}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Antwort fehlgeschlagen.");setReply("");await openTicket(selected);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Antwort fehlgeschlagen.")}finally{setBusy(false)}}
 async function changeStatus(status:Ticket["status"]){if(!selected)return;setBusy(true);try{const response=await fetch(`/api/support/tickets/${encodeURIComponent(selected)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Statusänderung fehlgeschlagen.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Statusänderung fehlgeschlagen.")}finally{setBusy(false)}}
 const active=tickets.find(ticket=>ticket.id===selected);
 return <div className="support-panel"><div className="support-columns"><section><h2>Support-Tickets <small>{tickets.length}</small></h2>{tickets.length?tickets.map(ticket=><button className={`support-ticket ${selected===ticket.id?"active":""}`} key={ticket.id} onClick={()=>void openTicket(ticket.id)}><b>{ticket.subject}</b><span>{ticket.requesterName||ticket.requesterEmail||(ticket.requesterType==="helper"?"Helferzugang":"Konto")} · {statusLabel[ticket.status]}</span><small>{new Date(ticket.updatedAt).toLocaleString("de-DE")}</small></button>):<p>Noch keine Tickets.</p>}</section><section><h2>Bearbeitung</h2>{active?<><p><b>{active.subject}</b><br/>{active.requesterEmail||active.requesterName||"Temporärer Helferzugang"}{active.eventId?` · Event ${active.eventId}`:""}</p><label>Status<select value={active.status} disabled={busy} onChange={event=>void changeStatus(event.target.value as Ticket["status"])}><option value="open">Offen</option><option value="in_progress">In Bearbeitung</option><option value="resolved">Erledigt</option></select></label><div className="support-thread">{messages.map(message=><article key={message.id}><b>{message.authorType==="support"?"Support":"Anfragende Person"}</b><time>{new Date(message.createdAt).toLocaleString("de-DE")}</time><p>{message.body}</p></article>)}</div><label>Antwort<textarea value={reply} onChange={event=>setReply(event.target.value)} rows={4} maxLength={4000}/></label><button disabled={busy||reply.trim().length<2} onClick={()=>void sendReply()}>Antwort senden</button></>:<p>Ticket auswählen, um Verlauf und Status zu bearbeiten.</p>}</section></div><section><h2>App-Fehlerberichte <small>{crashes.length} zuletzt</small></h2><p>Technische Berichte ohne Konto-ID, Fehlermeldung oder Zugangstoken. Automatische Löschung nach 30 Tagen.</p>{crashes.length?<div className="support-crashes">{crashes.map(crash=><details key={crash.id}><summary><b>{crash.errorKind}</b> · {crash.platform} · App {crash.appVersion} · {new Date(crash.occurredAt).toLocaleString("de-DE")}</summary><p>Quelle: {crash.source} · Fingerprint: <code>{crash.fingerprint.slice(0,16)}</code></p><pre>{crash.stackExcerpt||"Kein Stack verfügbar."}</pre></details>)}</div>:<p>Keine App-Fehlerberichte vorhanden.</p>}</section>{error&&<p role="alert" className="support-error">{error}</p>}</div>
}
