"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Building2,FileCheck2,KeyRound,Mail,MapPin,ReceiptText,ShieldCheck,Trash2,UserPlus} from "lucide-react";
import {RescueEdLogo} from "@/components/brand-logo";
import {PasswordField} from "@/components/password-field";
import {organizationTypeLabel,type OrganizationType} from "@/lib/organization-type";
import "./profil.css";

type Organization={name:string;organizationType:OrganizationType|null;billingEmail:string|null;billingStreet:string|null;billingHouseNumber:string|null;billingPostalCode:string|null;billingCity:string|null;canViewBilling:boolean;canEdit:boolean};
type Profile={id:string;name:string;email:string;role:"customer"|"organization_member"|"platform_owner"|"platform_staff";accountType:"organization"|"consumer";organization:Organization|null;canDeleteAccount:boolean};
type Acknowledgement={documentKey:string;version:string;acknowledgementType:"read"|"accepted";acceptedAt:string;title:string;signerId:string;signerName:string;own:boolean};
type LegalDocument={documentKey:string;title:string;version:string;pdfFileName:string|null};
type Member={id:string;name:string;email:string;status:string;emailVerifiedAt:string|null};
type Invoice={id:string;eventName:string;eventDate:string;recipientName:string;street:string;postalCode:string;city:string;email:string;amountCents:number;status:"pending"|"sent"|"paid"|"cancelled";createdAt:string;transmittedAt:string|null};
type Data={profile:Profile;acknowledgements:Acknowledgement[];legalDocuments:LegalDocument[];members:Member[];invoices:Invoice[]};

export default function ProfilePage(){
 const router=useRouter();
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[previewUrl,setPreviewUrl]=useState("");
 const loadProfile=useCallback(async()=>{const response=await fetch("/api/profile",{cache:"no-store"});if(response.status===401){router.replace("/");return null}const body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"Profil konnte nicht geladen werden.");setData(body);return body},[router]);
 useEffect(()=>{let active=true;fetch("/api/profile",{cache:"no-store"}).then(async response=>{if(response.status===401){router.replace("/");return}const body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"Profil konnte nicht geladen werden.");if(active)setData(body)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Profil konnte nicht geladen werden.")});return()=>{active=false}},[router]);

 async function saveOrganization(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/profile",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:values.get("name"),billingEmail:values.get("billingEmail"),billingStreet:values.get("billingStreet"),billingHouseNumber:values.get("billingHouseNumber"),billingPostalCode:values.get("billingPostalCode"),billingCity:values.get("billingCity")})}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Organisationsdaten konnten nicht gespeichert werden.");await loadProfile();setNotice("Organisations- und Rechnungsdaten wurden gespeichert.")}catch(reason){setError(reason instanceof Error?reason.message:"Organisationsdaten konnten nicht gespeichert werden.")}finally{setBusy(false)}}
 async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form),next=String(values.get("newPassword")||"");if(next!==values.get("repeatPassword")){setError("Die neuen Passwörter stimmen nicht überein.");return}setBusy(true);setError("");const response=await fetch("/api/profile/password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword:values.get("currentPassword"),newPassword:next})}),result=await response.json() as {error?:string};setBusy(false);if(!response.ok){setError(result.error||"Passwort konnte nicht geändert werden.");return}form.reset();setNotice("Passwort geändert. Alle bisherigen Sitzungen wurden beendet. Bitte erneut anmelden.")}
 async function inviteMember(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form);setBusy(true);setError("");const response=await fetch("/api/organization/member",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:values.get("name"),email:values.get("email")})}),result=await response.json() as {error?:string;previewUrl?:string};setBusy(false);if(!response.ok){setError(result.error||"Einladung fehlgeschlagen.");return}setPreviewUrl(result.previewUrl||"");setNotice("Einmaliger Passwortlink wurde für den Event-Benutzer vorbereitet.");await loadProfile()}
 async function manageMember(member:Member,action:"status"|"resend"){setBusy(true);setError("");const response=await fetch(`/api/organization/member/${encodeURIComponent(member.id)}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:action==="status"?JSON.stringify({status:member.status==="active"?"blocked":"active"}):"{}"}),result=await response.json() as {error?:string;previewUrl?:string};setBusy(false);if(!response.ok){setError(result.error||"Änderung fehlgeschlagen.");return}setPreviewUrl(result.previewUrl||"");setNotice(action==="resend"?"Ein neuer Einrichtungslink wurde versendet.":member.status==="active"?"Der Zugang wurde gesperrt.":"Der Zugang wurde wieder aktiviert.");await loadProfile()}

 const back=data?.profile.role==="platform_owner"||data?.profile.role==="platform_staff"?"/unternehmer":"/",organization=data?.profile.organization;
 return <main className="profile-page">
  <header><RescueEdLogo/><div><b>Mein Profil</b><span>RescueEd Alert</span></div><Link href={back}>← Zurück</Link></header>
  <div className="profile-wrap">
   {error&&<p className="profile-error" role="alert">{error}</p>}
   {notice&&<p className="profile-notice" role="status">{notice} {previewUrl&&<a href={previewUrl}>Lokalen Einrichtungslink öffnen</a>}</p>}
   {!data&&!error&&<p>Profil wird geladen …</p>}
   {data&&<>
    <section className="profile-card profile-identity"><h1>{data.profile.name}</h1><p><Mail size={17}/>{data.profile.email}</p><p><ShieldCheck size={17}/>{organization?.name||"RescueEd Alert"} · {roleLabel(data.profile.role)}</p></section>
    {organization?.canViewBilling&&<section className="profile-card">
     <h2><Building2/> Organisation und Rechnungsanschrift</h2><p className="profile-muted">Diese Stammdaten werden für neue Bestellungen und Rechnungen verwendet. Bereits ausgestellte Belege bleiben unverändert.</p>
     {organization.canEdit?<form className="profile-form profile-organization-form" key={`${organization.name}-${organization.billingEmail}-${organization.billingStreet}`} onSubmit={saveOrganization}>
      <label className="profile-field-wide">Organisation<input name="name" defaultValue={organization.name} maxLength={160} required/></label><label>Organisationsart<input value={organizationTypeLabel(organization.organizationType)} disabled/></label><label>Rechnungs-E-Mail<input name="billingEmail" defaultValue={organization.billingEmail||""} type="email" maxLength={254} required/></label><label>Straße<input name="billingStreet" defaultValue={organization.billingStreet||""} maxLength={160} required/></label><label>Hausnummer<input name="billingHouseNumber" defaultValue={organization.billingHouseNumber||""} maxLength={30} required/></label><label>PLZ<input name="billingPostalCode" defaultValue={organization.billingPostalCode||""} maxLength={20} required/></label><label>Ort<input name="billingCity" defaultValue={organization.billingCity||""} maxLength={120} required/></label><button className="profile-field-wide" disabled={busy}>Organisationsdaten speichern</button>
     </form>:<div className="profile-address"><p><Building2/>{organization.name} · {organizationTypeLabel(organization.organizationType)}</p><p><MapPin/>{organization.billingStreet} {organization.billingHouseNumber}, {organization.billingPostalCode} {organization.billingCity}</p><p><Mail/>{organization.billingEmail}</p><small>Änderungen kann nur das Organisations-Hauptkonto vornehmen.</small></div>}
    </section>}
    {organization?.canViewBilling&&<section className="profile-card"><h2><ReceiptText/> Rechnungen und Bestellungen</h2><p className="profile-muted">Alle kostenpflichtigen Event-Bestellungen dieser Organisation mit aktuellem Rechnungsstatus.</p>{data.invoices.length?<div className="profile-invoices">{data.invoices.map(invoice=><details key={invoice.id}><summary><span><b>{invoice.eventName}</b><small>{formatDate(invoice.eventDate)} · {formatDateTime(invoice.createdAt)}</small></span><strong>{formatMoney(invoice.amountCents)}</strong><em className={`invoice-status ${invoice.status}`}>{invoiceStatus(invoice.status)}</em></summary><div><p>Rechnungsempfänger: {invoice.recipientName}</p><p>{invoice.street}, {invoice.postalCode} {invoice.city}</p><p>Rechnungs-E-Mail: {invoice.email}</p><p>Referenz: {invoice.id}{invoice.transmittedAt?` · versendet am ${formatDateTime(invoice.transmittedAt)}`:""}</p></div></details>)}</div>:<p>Für diese Organisation wurden noch keine kostenpflichtigen Bestellungen gespeichert.</p>}</section>}
    <section className="profile-card"><h2><FileCheck2/> Rechtstexte</h2><p className="profile-muted">Hier können Sie die aktuell veröffentlichten Fassungen jederzeit aufrufen und Ihre gespeicherten Bestätigungen nachvollziehen.</p><div className="profile-legal-current">{data.legalDocuments.map(document=><article key={document.documentKey}><div><b>{document.title}</b><small>Version {document.version}</small></div><a href={`/rechtliches/${document.documentKey}`} target="_blank" rel="noreferrer">{document.pdfFileName?"PDF und Text öffnen":"Text öffnen"}</a></article>)}</div><details className="profile-acknowledgements"><summary>Gespeicherte Bestätigungen ({data.acknowledgements.length})</summary>{data.acknowledgements.length?<div className="profile-legal">{data.acknowledgements.map((item,index)=><article key={`${item.signerId}-${item.documentKey}-${item.version}-${index}`}><div><b>{item.title} · {item.version}</b><small>{item.own?"Von Ihnen":"Von "+item.signerName} {item.acknowledgementType==="read"?"gelesen":"bestätigt"} am {formatDateTime(item.acceptedAt)}</small></div><a href={`/rechtliches/${item.documentKey}`} target="_blank" rel="noreferrer">Aktuelle Fassung</a></article>)}</div>:<p>Noch keine persönlichen oder organisationsbezogenen Bestätigungen gespeichert.</p>}</details></section>
    <section className="profile-card"><h2><KeyRound/> Passwort ändern</h2><form className="profile-form" onSubmit={changePassword}><label>Bisheriges Passwort<PasswordField name="currentPassword" autoComplete="current-password" required/></label><label>Neues Passwort<PasswordField name="newPassword" autoComplete="new-password" minLength={12} required/></label><label>Neues Passwort wiederholen<PasswordField name="repeatPassword" autoComplete="new-password" minLength={12} required/></label><button disabled={busy}>Passwort ändern und Sitzungen beenden</button></form><Link href="/passwort-vergessen">Passwort vergessen? Link per E-Mail anfordern</Link></section>
    {data.profile.role==="customer"&&<section className="profile-card"><h2><UserPlus/> Weiteren Event-Benutzer anlegen</h2><p className="profile-muted">Genau ein zusätzlicher Benutzer kann Events dieser Organisation erstellen und verwalten. Er erhält keinen Zugriff auf das Betreiberkonto.</p>{data.members.length?<div className="profile-member"><b>{data.members[0].name}</b><span>{data.members[0].email} · {!data.members[0].emailVerifiedAt?"Einrichtung ausstehend":data.members[0].status==="active"?"Aktiv":"Gesperrt"}</span><div className="profile-member-actions">{!data.members[0].emailVerifiedAt?<button disabled={busy} onClick={()=>manageMember(data.members[0],"resend")}>Einladung erneut senden</button>:<button disabled={busy} onClick={()=>manageMember(data.members[0],"status")}>{data.members[0].status==="active"?"Zugang sperren":"Zugang entsperren"}</button>}</div></div>:<form className="profile-form" onSubmit={inviteMember}><label>Name<input name="name" maxLength={160} required/></label><label>E-Mail-Adresse<input name="email" type="email" required/></label><button disabled={busy}>Passwortlink senden und Benutzer anlegen</button></form>}</section>}
    {data.profile.canDeleteAccount&&<AccountDeleteSection onDeleted={()=>router.replace("/")} />}
   </>}
  </div>
 </main>;
}

function roleLabel(role:Profile["role"]){return ({customer:"Organisations-Hauptkonto",organization_member:"Event-Benutzer",platform_owner:"Betreiberkonto",platform_staff:"Unternehmer-Mitarbeiter"})[role]}
function formatMoney(cents:number){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(cents/100)}
function formatDate(value:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium"}).format(new Date(`${value}T12:00:00`))}
function formatDateTime(value:string){return new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function invoiceStatus(status:Invoice["status"]){return ({pending:"Offen",sent:"Versendet",paid:"Bezahlt",cancelled:"Storniert"})[status]}

function AccountDeleteSection({onDeleted}:{onDeleted:()=>void}){
 const [open,setOpen]=useState(false),[password,setPassword]=useState(""),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[deleted,setDeleted]=useState(false),[error,setError]=useState("");
 function close(){if(busy)return;setOpen(false);setPassword("");setConfirmed(false);setError("")}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!confirmed||!password)return;setBusy(true);setError("");try{const response=await fetch("/api/account/delete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password,confirmed})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"Das Konto konnte nicht gelöscht werden.");setPassword("");setDeleted(true)}catch(reason){setError(reason instanceof Error?reason.message:"Das Konto konnte nicht gelöscht werden.")}finally{setBusy(false)}}
 return <><section className="profile-card profile-delete-card"><h2><Trash2/> Account löschen</h2><p className="profile-muted">Wenn Sie RescueEd Alert nicht mehr nutzen möchten, können Sie Ihr Organisationskonto löschen. Vorher werden Passwort und ausdrückliche Bestätigung verlangt.</p><button type="button" onClick={()=>setOpen(true)}>Account löschen</button></section>{open&&<div className="profile-delete-overlay" role="presentation" onMouseDown={close}><section className="profile-delete-dialog" role="dialog" aria-modal="true" aria-labelledby="profile-delete-title" onMouseDown={event=>event.stopPropagation()}>{deleted?<><h2 id="profile-delete-title">Account wurde gelöscht</h2><p>Ihr Zugang wurde entfernt. Gesetzlich oder vertraglich erforderliche Nachweise bleiben getrennt im Löscharchiv erhalten.</p><button type="button" onClick={onDeleted}>OK</button></>:<form onSubmit={submit}><h2 id="profile-delete-title">Account endgültig löschen?</h2><p>Der Zugang wird sofort gesperrt, aktive Events werden beendet und eine erneute Anmeldung ist nicht möglich.</p><label>Aktuelles Passwort<PasswordField autoFocus autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} required/></label><label className="profile-delete-confirm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>Ich bestätige, dass mein Account und mein Zugang endgültig gelöscht werden sollen.</span></label><p className="profile-delete-retention">Vertrags-, Einwilligungs- und Abrechnungsnachweise können im Rahmen gesetzlicher Aufbewahrungspflichten weiter gespeichert bleiben.</p>{error&&<p className="profile-error" role="alert">{error}</p>}<div className="profile-delete-actions"><button type="button" disabled={busy} onClick={close}>Abbrechen</button><button type="submit" disabled={busy||!confirmed||!password}>{busy?"Wird gelöscht …":"Account endgültig löschen"}</button></div></form>}</section></div>}</>;
}
